### ISSUE TITLE
Font error 

### ISSUE THREAD

**Issue by vinonjat** [MicrosoftDocs/typography-issues#1045]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56b8cbdd-0a23-9f66-6f22-90317472e990
* Version Independent ID: c4dc5b5d-f391-fe19-d9d3-aeae9c9f5e7a
* Content: [Myanmar Text font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/myanmar-text)
* Content Source: [typographydocs/font-list/myanmar-text.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/myanmar-text.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by vinonjat** [comment]
![Front error](https://github.com/MicrosoftDocs/typography-issues/assets/33321510/30b1f9d5-e1aa-48ff-bbea-f07746272899)
![Uploading Front error.png…]()

**Comment by alib-ms** [comment]
Thank you for sharing the discrepancies with us. Some of the points you mentioned contradict the specific guidelines we received during the font creation process. For instance, we opted for rotated forms instead of squashed forms based on feedback from native speakers. Additionally, these forms are depicted in UTN11: [Representing Myanmar in Unicode](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.unicode.org%2Fnotes%2Ftn11%2FUTN11_4.pdf&data=05%7C01%7Calib%40microsoft.com%7C5395fa16324c4d62eedc08db6170c976%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638210909276227282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RZOWqHewyra1kl6KnsqvZMZm7TFJNYV%2FErE%2BEz%2F6mWk%3D&reserved=0)

**Comment by alib-ms** [comment]
However, I think following are issues in our font that should be fixed:
![image](https://github.com/MicrosoftDocs/typography-issues/assets/36778811/b20c0d0f-3272-4bf9-85ee-85892b4250af)

**Comment by Anontamon** [comment]
The nga letter in Mon is encoded U+105A ၚ and not U+1004 င as in Burmese. Independently, these
characters look very different. But in the context of something occurring below the character, the Mon nga (U+105A) loses its tail. Thus a Mon kinzi is encoded using U+105A U+103A U+1039. Since this is visually identical to the Burmese kinzi, where confusability is a concern (for example in International Domain Names), the Mon kinzi will not be usable and a misspelling may be necessary to get the desired name. In addition, the medial form of Mon nga is simply the tail: ္ၚ
/(U+1039 U+105A).
https://www.unicode.org/notes/tn11/UTN11_4.pdf
