### ISSUE TITLE
Name strings section was removed

### ISSUE THREAD

**Issue by Tyrben** [MicrosoftDocs/typography-issues#1068]
The previous documentation of type "Name strings" has disappeared of this page.
Especially the data format explanations.

It is still present in the Apple documentation
https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6name.html
section Name strings

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
The 'name' table spec isn't missing, but is here: <https://learn.microsoft.com/en-us/typography/opentype/spec/name>. It's unclear whether you meant something more specific. Closing since the issue, as I understand it, does not repro for me. If there is something more specific, please open an issue with specific details.
