### ISSUE TITLE
CFF2 CharString: explanation of edge hint encoding is unclear

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#1115]
In sections 2.1 Hints and 4.3 Hint Operators, encoding of edge hints is described, but is incomplete.

Stems are defined using pairs of numbers, *d1 d2*, where *d1* is a bottom or left edge and *d2* is a stem width. For edge hints, special width values of -20 and -21 are used. That much *seems* to be explained clearly enough.

However, section 4.3 continues with an example given in figure 4, which shows a glyph with a bottom edge at 100 and top edge at 500. From what is explained so far, one might expect that this pair of edge hints would be encoded as

> 100 -21 400 -20 **hstem**

But instead the spec states that the encoding is

> 121 -21 400 -20 **hstem**

If that's correct, then the details would seem to be a bit involved:

* For a bottom edge, the coordinate is obtained by adding *d1 + d2* (e.g., 121 + -21 = 100)
* For a top edge, the coordinate is *d1*.

If that is correct, then that should really be explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d36330ec-abae-705d-5953-83f246aa3536
* Version Independent ID: bbb4020e-f2a2-93a3-c02a-187ae372db28
* Content: [CFF2 CharString Format (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/cff2charstr)
* Content Source: [typographydocs/opentype/spec/cff2charstr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff2charstr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by skef** [comment]
Yeah, that diagram and variations of the language go back a long way in the various specs. I've always suspected that they wanted the values this way because of an implementation detail (maybe to force the ghost stems into the order for the algorithm of the time) and then tried and failed to play it off as intuitive. 

The way I remember the convention is that when the delta/length pairs are unpacked each ghost stem still has an absolute top and bottom, just defined in reverse, and a top edge hint is defined by the top of its stem while a bottom edge hint is defined as the bottom of its stem. Maybe that can be turned into some quasi-intuitive language, then clarified by noting as you more or less do that the top edge hint will be at the location of the unpacked delta while the bottom edge hint will be at the location of the unpacked edge length.

**Comment by Lorp** [comment]
I attempted to clarify this in the CFF2 spec rewrite that Adobe commissioned, and which is now in the OFF spec:

> 5.3.3.10.7 Hints 
> …
> The hint stem operators (hstem, vstem, hstemhm and vstemhm) define horizontal or vertical hints for stems and edges. Each stem is defined as a pair of numbers: its bottom or left edge followed by its top or right edge. Stems for a particular orientation are encoded by:
> •	sorting the pairs by bottom coordinate (for horizontal stems) or left coordinate (for vertical stems);
> •	concatenating the pairs into a sequence of numbers;
> •	using relative values: the first number is relative to 0, and all other numbers are relative to the previous number.

**Comment by PeterCon** [comment]
For [OT 1.9.1 alpha](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/cff2), I've added the following paragraph in the discussion with edge hints --- this assumes that the current values in the example are correct:

> If interpreted as a pair of edges, a negative width would imply that the second edge of the pair is lower or farther left than the first edge of the pair. When deriving the coordinates of an edge, the leftmost or lowest implied edges are used for left and bottom edges, while the rightmost or highest implied edges are used for right and top edge. Thus, for a left or bottom edge, the initial edge value *and* the negative width value are combined to derive the edge hint coordinate, while for a right or top edge, only the initial edge value is used. So, for example, to define a bottom edge at 100, the encoded representation would use the values 121 -21; to define a top edge at 700, the encoded representation would be 700 -20.

I think that is consistent with the figure in an as-clear-as-possible way.

@Lorp The sentence "For the purposes of sorting, the first coordinate implied by an edge hint is considered its bottom or left coordinate" is very unclear: what is meant by *first coordinate implied*? I didn't change the wording in the OT1.9.1 draft while incorporating what you prepared since it didn't make the existing problem worse and I couldn't figure out an improvement. But after reading your comment, I have an idea of what you meant, so will work on how to make the wording clearer --- though it would be nice to get confirmation as to what Adobe's CFF(2) rasterizer expects.

E.g., suppose different parts of a glyph have a stem between 103 and 113 (*stem1*), and another between 115 and 125 (*stem2*), with another part having an edge (*edge1*) at 100, how should the operands be ordered?

> 121 -21 3 10 2 10   
> (= *edge1*, *stem1*, *stem2)

or

> 103 10 2 10 -4 -21  
? (= *stem1 stem2 edge1*) 

(Or something else?)

**Comment by PeterCon** [comment]
In OT1.9.1 alpha (and in a contribution I'm preparing for OFF), I've revised the wording of that paragraph (last in what lorp quoted) to the following&mdash;which I hope reflects a correct understanding. (This follows the extra paragraph I added, mentioned above.)

>Because the width value of an edge hint represents *left*, *bottom*, *top* or *right* rather than an actual measurement, edge hints are never considered to overlap other stems. For purposes of sorting stem and edge hints, left and bottom edges are sorted based on the actual edge coordinate, not the first value used to encode the edge hint (*100* in the previous bottom edge example, not *121*).

**Comment by Lorp** [comment]
I think this is a useful clarification. I had to read the spec several times to arrive at the wording I did (and I think I raised it with Adobe people, but it's a while ago and I'm not sure).

**Comment by PeterCon** [comment]
See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
