### ISSUE TITLE
CFF2 CharString: Description of number format 28 is inconsistent

### ISSUE THREAD

**Issue by wezm** [MicrosoftDocs/typography-issues#1124]
In "Table 1. CFF2 CharString Encoding Values" the following is shown, which is consistent with the [Type 2 CharStrings PDF from Adobe](https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf):

| CharString Byte Value | Interpretation            | Number Range Represented | Bytes Required |
|-----------------------|---------------------------|--------------------------|----------------|
| 28                    | next 2 bytes are an int16 | -32768 to +32767         | 3              |

Later in [Appendix A](https://learn.microsoft.com/en-us/typography/opentype/spec/cff2charstr#appendix-a-cff2-charstring-command-codes), "Table 2. One-byte CFF2 Operators":

| Dec | Hex | Operator  | Note                                                                                                |
|-----|-----|-----------|-----------------------------------------------------------------------------------------------------|
| 28  | 1c  | <numbers> | First byte of a 3-byte sequence specifying an unsigned integer value (next two bytes are a uint16). |

Note that appendix says the value is unsigned whereas the first table says it's signed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d36330ec-abae-705d-5953-83f246aa3536
* Version Independent ID: bbb4020e-f2a2-93a3-c02a-187ae372db28
* Content: [CFF2 CharString Format (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/cff2charstr)
* Content Source: [typographydocs/opentype/spec/cff2charstr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff2charstr.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by Lorp** [comment]
The CFF2 CharString number encodings are similar but not identical to the CFF2 DICT number encodings. In the revised CFF2 spec, the two tables are merged so that these differences are called out more clearly.

Initial byte b0 | Value range |  Value calculation | Size in bytes | Usage |
| :--- | :--- | :--- | :--- | :--- |
|  32 to 246 |  -107 to 107 |  b0 - 139 | 1 | both |
|  247 to 250 |  108 to 1131 |  (b0 - 247) &ast; 256 + b1 + 108 | 2 | both |
|  251 to 254 |  -1131 to -108 |  -(b0 - 251) &ast; 256 - b1 - 108 | 2 | both |
|  28 |  -32768 to 32767 | interpret b1 and b2 as _int16_ | 3 | both |
| 255 | -32768 to (32768 - 1/65536) | interpret b1 to b4 as *Fixed* | 5 | *CharString* only |
|  29 |  -(2^31) to (2^31 - 1) |  interpret b1 to b4 as *int32* | 5 | *DICT* only |
| 30 | any real number | following bytes are *Binary Coded Decimal* | unlimited | *DICT* only |

**Comment by wezm** [comment]
> In the revised CFF2 spec

Is this an unpublished version? If so, then does that imply that the discrepancy has been resolved? I.e. there is no mention of `uint16` now, only `int16`.

**Comment by Lorp** [comment]
This revised table is published here: https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/cff2 . It is also published as part of the Open Font Format specification.

It was around two years ago that I edited the CFF2 specification, but there were indeed some inconsistencies. These were resolved in consultation with Adobe and Microsoft engineers.

**Comment by PeterConstable** [comment]
This is all resolved in drafts for OpenType 1.9.1. Note that the CFF2 CharString appendix will be deleted, with all of the content merged into the CFF2 table chapter. See https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/cff2 for the combined content. 

(And thanks to @Lorp and Adobe for the large contribution on improving these specs.)

**Comment by PeterConstable** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by wezm** [comment]
1.9.1 changes look good 👍
