### ISSUE TITLE
Miscounted GSUB lookups

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#20]
&gt;OpenType Layout has seven types of GSUB lookups

It has eight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version. Thanks!

**Comment by karenzshea** [comment]
GSUB table page describes only seven substitution types though (https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#overview) or is that section referring to something else?

**Comment by PeterCon** [comment]
The GSUB lookup type enumeration has eight values defined, but there are only seven distinct lookup actions.

The wording can be improved to avoid this confusion:

"The GSUB table supports seven types of glyph substitution actions..."

Compare with corresponding wording in the GPOS chapter.

Couple perhaps add this note after the list of substitution types:

"Note that the GSUB lookup type enumeration includes an additional type, Extension Substitution. This provides a format extension mechanism, allowing reference to a lookup subtable using a 32-bit offset rather than 16-bit. It does not provide an additional type of substitution action, however."

**Comment by karenzshea** [comment]
Thanks for the clarification, that makes it clear.

**Comment by PeterCon** [comment]
Fixed for next version.
