### ISSUE TITLE
More detailed info needed

### ISSUE THREAD

**Issue by Mrmohanak** [MicrosoftDocs/typography-issues#225]
We need more info about this topic in details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3625191-cbf0-c30b-2f89-60ed8c11d4d7
* Version Independent ID: 7e7a7e77-9514-fcc9-82e8-36335e0f222e
* Content: [Legacy Arabic Font Encodings - Typography](https://docs.microsoft.com/en-us/typography/legacy/legacy_arabic_fonts#feedback)
* Content Source: [typographydocs/legacy/legacy_arabic_fonts.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/legacy/legacy_arabic_fonts.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **petercon**

**Comment by Mrmohanak** [comment]
https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/legacy/legacy_arabic_fonts.md

Not found on Github!

**Comment by alibasi** [comment]
Hi, thank you for your feedback. Can you be more specific.

**Comment by DarrenHoffman** [comment]
I am not familiar with the Arabic language and/or writing system, but I am trying to write some code to support these legacy fonts none-the-less, and **one thing** that appears to be **missing** from the brief documentation is that certain combinations of multiple characters are mapped to a single glyph in these fonts, such as the two character string U+0644 U+0627 maps to the single glyph 0xF2DC, rather than to the two glyphs consisting of the Initial form of U+0644 and the Final form of U+0627.

Now for all I know at this point the difference is merely stylistic and the typical Arabic language reader would not bat an eye, however I wouldn't be surprised if the difference matters a great deal. Either way it seems like this is something that should be included in the documentation at https://docs.microsoft.com/en-us/typography/legacy/legacy_arabic_fonts. But that page only covers the mapping of a single character to one of the four single character forms.

**Comment by tiroj** [comment]
The legacy Arabic font model uses character level mapping from standard Unicode Arabic code block input to Unicode Arabic Presentation Forms code block output. Yes, this involves both mapping of individual characters to corresponding positional joining presentation forms, and also mapping of multiple characters to individual ligature presentation forms. Some of the ligature presentation forms are preferred stylistic rendering for specific combinations of letters, but a few are orthographically required, notably the lam_alif combination.

Question: why do you need to support these legacy fonts in your code? There are much, much better ways to make Arabic fonts now, and as a result much better Arabic fonts to choose from.

**Comment by tiroj** [comment]
Question: why do you need to support these legacy fonts in your code? The approach they use for Arabic shaping is really clumsy and limited, and there are a lot of better options available now, both in terms of ways of making fonts and the quality of the resulting fonts to choose from.
