### ISSUE TITLE
COLR table constraints re glyph advance width / vertical origin

### ISSUE THREAD

**Issue by behdad** [MicrosoftDocs/typography-issues#250]
&gt; "The layered glyphs are explicitly defined in bottom-up z-order and each of their advance widths must match those of the base glyph."

I suggest we remove this.  There's no need for this.

&gt; If the font has vertical metrics, the associated layer glyphs must also have the same advance height and vertical Y origin as the base glyph.

Same here.  I suggest we note that layers are aligned using their horizontal origin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be879f46-c026-4a9d-1156-a3c98ae8f429
* Version Independent ID: 28be1ce2-e487-b652-632f-e4dc5bb17f42
* Content: [COLR - Color Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/colr#feedback)
* Content Source: [typographydocs/opentype/spec/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/colr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by khaledhosny** [comment]
IIRC, DirectWrite would produce some unexpected output of the layers didn't match the advance width of the base glyph, so at least there is one engine that actually expects this.

**Comment by behdad** [comment]
I suppose that's what happens when spec is written to match implementation instead of other way around...

**Comment by PeterCon** [comment]
Are you suggesting to remove mention of

* bottom-up z-order?
* matching advance widths?
* both?

**Comment by behdad** [comment]
> * matching advance widths?

Just this part.

**Comment by behdad** [comment]
> Just this part.

Becomes particularly problematic with COLRv1 when we add transforms. cc @rsheeter

**Comment by niklasb-ms** [comment]
The advance width requirement is for right-to-left glyph runs.

One of the design goals was that it should be possible to translate the original (color) glyph run to a series of layer glyph runs that can be correctly rendered by a non-COLR-aware text engine. For example, when printing, the layer glyph runs can be serialized to XPS and correctly rendered by an XPS rasterizer (possibly embedded in a printer) that doesn't understand COLR.

Glyph runs in XPS (and in DirectWrite) have a bidi level, and the glyphs are in logical rather than visual order. Correctly positioning a glyph in a right-to-left run requires knowing the advance width of the glyph (the actual width from the font, not the width specified by the glyph run, since the latter may have been modified by justification). The constraint on advance widths is so a COLR processor can translate a right-to-left run to a series of right-to-left layer runs and still have the glyphs line up correctly. The constraint on advance height and vertical Y origin is similar, but for vertical/sideways text.

Since there are already implementations that depend on this, I think we should keep the requirement for glyphs referenced by version 0 layer records. However, I'm fine with eliminating this requirement for glyphs that are only referenced by version 1 records.

**Comment by behdad** [comment]
> The constraint on advance widths is so a COLR processor can translate a right-to-left run to a series of right-to-left layer runs and still have the glyphs line up correctly.

That constraint is NOT required for such processing. You are just documenting a limitation of one implementation.

**Comment by niklasb-ms** [comment]
> > The constraint on advance widths is so a COLR processor can translate a right-to-left run to a series of right-to-left layer runs and still have the glyphs line up correctly.
> 
> That constraint is NOT required for such processing. You are just documenting a limitation of one implementation.

I agree are other ways to implement it where the constraint is not necessary. The constraint was included in the spec to simplify a possible implementation approach. I don't think it's unusual for a spec to consider possible implementations and include such provisions.

I'd be OK with changing DirectWrite to not depend on this in the future, but there would still be existing systems out there for quite a few years to come that depended on it. For that reason, I don't think it's prudent to remove the constraint from the spec insofar as it applies to COLRv0 processors.

**Comment by behdad** [comment]
> I don't think it's unusual for a spec to consider possible implementations and include such provisions.

Except that that's not what happened here. Microsoft has a glaring record of putting into spec what was *convenient* for their implementation. And by "convenient" I mean, lazy. This then makes the format inferior for a long long time. I have documented many such decisions:

https://lists.aau.at/pipermail/mpeg-otspec/2020-August/001925.html
https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002017.html

**Comment by niklasb-ms** [comment]
> > I don't think it's unusual for a spec to consider possible implementations and include such provisions.
> 
> Except that that's not what happened here. Microsoft has a glaring record of putting into spec what was _convenient_ for their implementation. And by "convenient" I mean, lazy. This then makes the format inferior for a long long time. I have documented many such decisions:
> 
> https://lists.aau.at/pipermail/mpeg-otspec/2020-August/001925.html
> https://lists.aau.at/pipermail/mpeg-otspec/2020-August/002017.html

I don't want to get drawn into an argument about whether including this provision was a bad decision. Perhaps it was. The question is whether removing it _now_ is a good decision.

The disadvantage of removing the constraint is it would break compatibility with an existing implementation in a way that will produce wrong visual results for users in right-to-left contexts.

An advantage is it would simplify the spec. That's a good thing, but not enough reason on its own to justify breaking compatibility IMO. Are there other advantages? Do we have reason to believe that the constraint on advance widths is burdensome to designers of color fonts?

**Comment by behdad** [comment]
> The question is whether removing it _now_ is a good decision.

I'm fine with keeping the recommendation for v0 table.

**Comment by PeterCon** [comment]
Appears that no change is needed, so closing.
