### ISSUE TITLE
WWS Family Name: Example inconsistent with defintion

### ISSUE THREAD

**Issue by famoser** [MicrosoftDocs/typography-issues#255]
It is stated that the WWS Family Name should "provide a WWS-conformant family name in case the entries for IDs 16 and 17 do not conform to the WWS model."  

But the example states that this entry may contain “Minion Pro Caption” and “Minion Pro Display” for fonts which have in the entry ID 16 “Minion Pro”.

It should probably be the other way around; the WWS Family Name would contain “Minion Pro” for the two fonts used in the example, while the Typographic name (ID 16) would then contain “Minion Pro Caption” and “Minion Pro Display”.

This would also be in line with the definition and description of the WWS Subfamily Name.

If my assumptions are correct, then also the wording in the full example should be adjusted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name#feedback)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
No, the spec is correct on this point.

Name IDs 21/22 are for use by clients that assume a WWS model for font families. A WWS family model means that a weight distinction (Regular, Bold, etc.), or a width distinction (Narrow, Extended, etc.) or a slope distinction (Oblique, etc.) are *sub-family* distinctions. But anything else is a family-level distinction. For example, optical size distinctions such as Caption or Display are handled as family distinctions in a WWS model. 

Name IDs 16 and 17 are not limited to a WWS family model. So any distinction the font designer considers to be part of the same family can be treated as a sub-family distinction.

For the examples of Minion Pro Caption and Minion Pro Display, the font designers (Adobe) consider the typographic family to be "Minion Pro", and so that is the value they set for Name ID 16; "Caption" and "Display" are sub-family distinctions and so are used for Name ID 17. But when the same fonts need to be projected into a WWS family model, "Caption" and "Display" are not sub-family distinctions in the WWS model, and so "Minion Pro Caption" and "Minion Pro Display" are treated like separate families, with those labels set using Name ID 21.

I'll close this issue as not requiring any changes. If you think there is an issue that I misunderstood, feel free to open another issue.
