### ISSUE TITLE
Description of some constants in MATH table needs clarification

### ISSUE THREAD

**Issue by SergeyMalkin** [MicrosoftDocs/typography-issues#285]
Various shift values in constants section are applied from default position on baseline. Spec should be clear about this. Otherwise, things like fraction numerator shift-up can be interpreted as offset from math axis (i.e. position of fraction bar).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0076fd2-52b0-2989-3142-fd9e456b9514
* Version Independent ID: 4aef8fa3-2ad3-7933-5a77-0a7473e66112
* Content: [MATH - The mathematical typesetting table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/math)
* Content Source: [typographydocs/opentype/spec/math.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/math.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by fred-wang** [comment]
Not sure whether I should open a separate issue for this, but there is currently some discussions in https://github.com/mathml-refresh/mathml/issues/69 about what the default values should be in MathML Core. The relevant section in the spec is https://mathml-refresh.github.io/mathml-core/#layout-constants-mathconstants

Last years I had created a table with some possible values from TeX, OpenType MATH, MathPlayer and browsers: https://mathml-refresh.github.io/math-constants.html

More specifically, I have three questions for Microsoft:

* What is "the default rule thickness" suggested in the spec? (see first row in the table above) 

* Why is there a suggestion for radicalKernAfterDegree and radicalDegreeBottomRaisePercent but not for radicalKernBeforeDegree? Again, the corresponding row in the table above uses 5/18 em, −10/18 em and 60%.

* For spaceAfterScript, what does "0.5pt for a 12pt font" mean? How to interpret that for different font size?

**Comment by SergeyMalkin** [comment]
- Default rule thickness: there is no recommended value, it completely depends on typeface design. It makes sense to make it equal to thickness of minus sign
- Radical kerning: recommended values com from TeX. It was too long time ago to remember, but it is probably just an omission.
- spaceAfterScript is a constant in TeX that doesn't change with font size. So we fixed some common body font size as a base for 0.5pt /scriptspace, but did no go as far as recommend 1/24em ratio. In Word all constants including this one are scaled linearly with font size.

**Comment by fred-wang** [comment]
@SergeyMalkin Thanks for the feedback. More comments:

>     * Default rule thickness: there is no recommended value, it completely depends on typeface design. It makes sense to make it equal to thickness of minus sign

Someone suggested underlineThickness form https://docs.microsoft.com/en-us/typography/opentype/spec/post#header which should be also the same as https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ss and the thickness of the underscore character (U+005F LOW LINE). Do you think you could add a suggestion like this as the fallback value?

>     * Radical kerning: recommended values com from TeX. It was too long time ago to remember, but it is probably just an omission.

Thanks. So I guess you plan to fix that?

>     * spaceAfterScript is a constant in TeX that doesn't change with font size. So we fixed some common body font size as a base for 0.5pt /scriptspace, but did no go as far as recommend 1/24em ratio. In Word all constants including this one are scaled linearly with font size.

Suggesting 1/24em sounds good to me as we need the fallback to work for arbitrary font size.

**Comment by flideros** [comment]
I am experimenting with the math table values in a WPF control. There might be something in my code you could use visualize the table values. https://github.com/flideros/fSharp-Symbolic-Math-Lab

**Comment by PeterCon** [comment]
@SergeyMalkin @fred-wang : The opening comment for this issue pertained to "shift" values. But the discussion later brought up rule thickness, radical kerning and spaceAfterScript. It's not clear what changes are being requested. If changes are desired in regard to any of these other three items, I think it would be helpful to open a separate issue for each, and revise the title of this to focus on the "shift" issue.

**Comment by PeterCon** [comment]
@fred-wang : I'm wondering if you're monitoring and can provide clarification. Thanks.

**Comment by fred-wang** [comment]
@PeterCon Sorry I missed your previous comment. I can open separate issues later.

**Comment by PeterCon** [comment]
@fred-wang Thanks. 

I'm also trying to get clarity on what example wasn't currently clear in regard to "shift", and wonder if you could provide some clarification on that.

As I read the spec, I understand these as positioning adjustments, with the values given as the size of the position adjustment from the initial glyph position. From Sergey's initial comment when opening the issue, he mentioned potential ambiguity wrt baseline vs. math axis, though if the values are adjustments (rather than resulting offsets) it doesn't seem ambiguous to me. But apparently the current wording wasn't as clear enough to avoid confusion for some (hence probably many).

If you can clarify was was creating confusion, that would help.

Thanks

**Comment by fred-wang** [comment]
@PeterCon I think in general https://docs.microsoft.com/en-us/typography/opentype/spec/math does not really say how to interpret the parameters, so one has to read the TeXBook and figure out what is the correspondence and interpretation. Ideally, the spec should be self-contained.

Regarding shifts, these are the only things we have:

"Shift — Defines a vertical shift applied to an element sitting on a baseline."
"Standard shift up/down applied"

which I can agree is understandable once you already know how to place things, but not sure it really discards an interpretation like "amount of which the baseline of the numerator is shifted away from the math axis". I believe https://www.tug.org/~vieth/papers/bachotex2009/ot-math-paper.pdf was initially used by Gecko/WebKit, but Figure 2 is confusing because the math axis is the same as the baseline.

Similarly, in table 2 of this pdf the StretchStackTopShiftUp/StretchStackTopShiftUp are said to match zeta11 and zeta12 and figure 1 draws these zeta's with respect to the ink bottom/top of the base, not with respect to the baseline.

**Comment by PeterCon** [comment]
Proposed fixes for the next version:

In the text immediately prior to the table defining the MathConstants table:

>* **Shift** — Defines a vertical shift applied to an element sitting on a baseline.<ins> Note that the value is an amount of *adjustment* to the position of an element, not the resulting distance from the baseline or other reference line.</ins>
>* **Dist** — Defines a distance between baselines of two elements.
>
><ins>The descriptions for several fields refer to *default rule thickness*. Layout engines control how rules are drawn and how their thickness is set. It is recommended that rules have the same thickness as a minus sign, low line, or a similar font value such as [OS/2.yStrikeoutSize](os2.md#ystrikeoutsize). For fields that are described in reference to default rule thickness, one of these should be assumed.</ins>

Descriptions of spaceAfterScript and radicalKernBeforeDegree:

><table>
<tr>
<td>MathValueRecord</td>
<td>spaceAfterScript</td>
<td>Extra white space to be added after each subscript and superscript. Suggested: 0.5 pt for a 12 pt font.<ins> (Note that, in some math layout implementations, a constant value, such as 0.5 pt, may be used for all text sizes. Some implementations may use a constant ratio of text size, such as 1/24 of em.)</ins></td></tr>
<tr><td>...</td></tr>
<tr>
<td>MathValueRecord</td>
<td>radicalKernBeforeDegree</td>
<td>Extra horizontal kern before the degree of a radical, if such is present.<ins> Suggested: 5/18 of em.</ins></td>
</tr>
</table>
