### ISSUE TITLE
vertTypo{Ascender,Descender} descriptions

### ISSUE THREAD

**Issue by emuller-amazon** [MicrosoftDocs/typography-issues#3]
The description of vertTypoAscender is:

---
The vertical typographic ascender for this font. It is the distance in FUnits from the ideographic em-box center baseline for the vertical axis to the right of the ideographic em-box and is usually set to (head.unitsPerEm)/2. For example, a font with an em of 1000 fUnits will set this field to 500. See the baseline section of the OpenType Tag Registry for a description of the ideographic em-box.
---

 "to the right": shouldn't that be "to the top" ?

Similarly, vertTypoDescender:

---
The vertical typographic descender for this font. It is the distance in FUnits from the ideographic em-box center baseline for the horizontal axis to the left of the ideographic em-box and is usually set to (head.unitsPerEm)/2. For example, a font with an em of 1000 fUnits will set this field to 500.
---

"to the left" -&gt; "to the bottom"?

In addition, following the model of OS/2.typo*, I think the typical value should be "-500", not "500". This would also match the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312f3284-9ca3-b310-e0e7-d2912d674f88
* Version Independent ID: 81687336-c575-3041-f241-b7ff15b49965
* Content: [vhea — Vertical header table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/vhea)
* Content Source: [typographydocs/opentype/spec/vhea.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/vhea.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Interesting. The table was originally defined by Apple, and the definition in OT1.8.2 matches that in Apple's TrueType Reference Manual in this regard.

(Apple's doc doesn't use the "ideographic em box" term, though. And they give -500 for the vertTypoDescender example. Kozuka Mincho Pro has -500, which corroborates a -ve value for the field.)

I think this is correct since this is a _line_ metric value, used to determine default baseline-to-baseline distance. The fact that the field names use "ascender" and "descender" may be misleading. Since ideograph glyphs are not rotated relative to the page in vertical layout, but are rotated relative to the baseline (since the baseline is rotated relative to the page), it is the right and left edges of the ideographic em box that face toward the preceding and following lines.

So, I'm not sure the right vs. top and left vs. bottom issue is actually an error.

I do think there is an error in the vertTypoDescender description in referring to "for the horizontal axis" (which would mean horizontal layout).

Hence, for OT 1.8.3, I'll correct the vertTypoDescender description for two issues: 
- "horizontal axis" -> "vertical axis"
- "500" -> "-500"

Btw, this section was last revised in 2001 for OT 1.3!

**Comment by emuller-amazon** [comment]
You are right about left. It should be left alone (of course, the whole description sort of falls apart for proportional fonts, but that's another story). I agree with your proposed changes.

Thanks.
