### ISSUE TITLE
Looking for clarification on WWS naming scheme

### ISSUE THREAD

**Issue by BoldMonday** [MicrosoftDocs/typography-issues#324]
The current OpenType spec (1.8.3) describes the mechanism for making fonts compliant to the WWS naming scheme:
https://docs.microsoft.com/en-us/typography/opentype/spec/name
In the spec the term WWS is consistently described as `Weight Width Slope`.

Yet the one example that the spec shows (Arial) is showing a different order:
"Arial Narrow Bold Italic" has a Width Weight Slope order.
https://docs.microsoft.com/en-us/typography/opentype/spec/namesmp

Two questions:
1. Does the order of items matter in the WWS naming scheme?
2. If the order matters then what is that order?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90b91c1f-532f-1306-070f-ee41c08bb4df
* Version Independent ID: 499f13e8-8f4d-3f55-0c36-481a6de52db2
* Content: [Name string examples - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/namesmp)
* Content Source: [typographydocs/opentype/spec/namesmp.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/namesmp.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
When the spec refers to "WWS" or "weight width slope", that is not intended as a commendation on ordering of labels within a name.

There is some discussion of axis ordering in the STAT chapter (https://docs.microsoft.com/en-us/typography/opentype/spec/stat), since a field is provided to indicated ordering axes. This is relevant to your question:

"The axis ordering field allows the font developer to influence... the ordering of axis-value descriptors when face names are projected into different font-family models." 

It goes on to describe applications that may assume a four-member R/B/I/BI family model, or a WWS model (as opposed to a more general model with unlimited axes). If a face name contains labels pertaining to axes that don't fit into the app's family model, it has to pull those labels into a constructed family name. Later in that page, mid-way in the Axis Value Tables section, there is a note recommending that "that width, weight and italic/oblique descriptors always be placed last in a subfamily name, to minimize differences in how names will appear in different appliations [sic] that use different family models".

The same principle could be applied to width vis-à-vis weight and italic/oblique, but that is not called out since R/B/I/BI family and sub-family names can be defined directly using name IDs 1 and 2 (as described on this page and on the STAT page).

Now, it appears there is a general convention that italic/slant labels always follow weight and width. But there is less consistency in past practice regarding relative ordering of weight and width. On the one hand, "Myriad Pro Bold Condensed", but on the other hand "Arial Narrow Bold". If your target audience frequently use apps that follow a R/B/I/BI model, then a width-weight order may provide more consistency across their applications. But otherwise, a weight-width order is fine and may even be more commonly used in fonts.
