### ISSUE TITLE
Transparent holes in font "Bahnschrift" caused by fill-rule: even-odd

### ISSUE THREAD

**Issue by Grenbur** [MicrosoftDocs/typography-issues#398]
![screenshot Bahnschrift issue](https://user-images.githubusercontent.com/63538959/79227434-291dcb00-7e60-11ea-8045-7b20c8b83338.PNG)

As you can see transparent holes are created where the lines overlap. According to the following feedback:
https://gitlab.com/inkscape/inbox/-/issues/2243#note_322119038
This is caused by fill-rule: even-odd. Is it something that can be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0aa22d-ec65-a36b-3a23-ca87e18ada28
* Version Independent ID: 05d3eb61-7b3c-24f6-dc0e-cb9d02e1c3a0
* Content: [Bahnschrift font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/bahnschrift)
* Content Source: [typographydocs/font-list/bahnschrift.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/bahnschrift.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by aaronbell** [comment]
Hi! I'm the designer of Bahnschrift. (I posted this on the Gitlab thread, but you may also want to ask them to re-open the issue).

Bahnschrift is what's called a "variable font", which is to say that multiple font styles are included in the same font file and an application can modify aspects of the font along various axes. For more information about this, I suggest taking a look at [Axis Praxis](https://www.axis-praxis.org) and [Microsoft Font Variations Overview](https://docs.microsoft.com/en-us/typography/opentype/spec/otff).

In order to enable this kind of functionality, overlaps have not been removed in the font (which is valid within font standards). However, from the image above it appears that Inkscape expects outlines to be removed in fonts, and so is rendering the outlines incorrectly. As such, this is an issue that Inkscape needs to resolve.

Please let me know if there's anything more I can do to help :)

**Comment by alib-ms** [comment]
Thank you for the feedback. As Aaron has pointed out this is an application issue, therefore closing this issue.
