### ISSUE TITLE
Example of glyph variation uses the same glyphs

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#44]
>The character “capital letter A” is represented by the glyph “A” in Times New Roman Bold and “A” in Arial Bold.

There is no markup in this sentence, so the “A”s look identical, but it is worded as if there is a visible difference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It's been that way since at least OpenType 1.4. On the old site, the pages could have had styling to format those characters with different fonts, but the didn't. The new site doesn't provide a way to control font styling on spans. So, it's odd and maybe a tiny bit confusing for a reader paying close attention, but it's been that way for at least 16 years.

**Comment by PeterCon** [comment]
Reworded in the next version to work around this issue.
