### ISSUE TITLE
Remove inaccessible links

### ISSUE THREAD

**Issue by davelab6** [MicrosoftDocs/typography-issues#483]
At the top of each OpenType table page, there is a list of contributors with Github avatars:

<img width="2012" alt="Screen Shot 2020-08-12 at 1 38 19 PM" src="https://user-images.githubusercontent.com/261579/90048178-25307700-dca1-11ea-96f1-feb4ce38726b.png">

But this links to the source of the page, which 404s:

<img width="2012" alt="Screen Shot 2020-08-12 at 1 38 23 PM" src="https://user-images.githubusercontent.com/261579/90048182-2792d100-dca1-11ea-9237-389e1b0e85ee.png">

It seems the link is not broken, but is merely pointing to what I expect is a private repo :( 

<img width="2012" alt="Screen Shot 2020-08-12 at 1 38 26 PM" src="https://user-images.githubusercontent.com/261579/90048189-29f52b00-dca1-11ea-8dc1-5780954c01d1.png">

It would be good to avoid the OpenType spec website containing broken links, especially those that tease visitors with links to private repos :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6fbd1f5-de25-b53e-7547-606779225859
* Version Independent ID: 120d721b-e602-b760-aad2-3f1a91997d4c
* Content: [MERG — Merge Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/merg)
* Content Source: [typographydocs/opentype/spec/merg.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/merg.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for the feedback. You are right the link is not broken, but is merely pointing to a private repo. I will report this to the team and update pages accordingly.

**Comment by alerque** [comment]
Please also report to the team that the whole repo should just be removed from it's private black-box existence; taking feedback via Github issues everybody's time could be better spent with direct contributions is –at this point– far beyond silly. Even with no other changes (that would also be good) such as changes in licensing or what changes you actually choose to apply it would still save everybody time and confusion to comment on the source rather than raising flags in another castle.

**Comment by PeterCon** [comment]
Not immediately actionable so closing.
