### ISSUE TITLE
'opbd' is weird

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#578]
> For GIDs found in the 'opbd' coverage table, the application calls one of two related tables, depending on the position of the glyph. For glyphs at the left end of a horizontal line, it calls the ['lfbd'](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#lfbd) table, for glyphs at the right end of a horizontal line, it calls the ['rtbd'](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#rtbd) table.

This implies that the substitutions in an 'opbd' lookup are ignored: only its coverage table is consulted, and the substitutions are actually done by 'lfbd' and 'rtbd'. Is that the intended interpretation of 'opbd'? Is this an interoperable requirement in practice?

It also implies that the coverage tables of 'lfbd' and 'rtbd' lookups are either completely ignored or are filtered through the coverage table of 'opbd' lookups. If a glyph at the left end of a line is in the coverage table of a 'opbd' lookup but _not_ in the coverage table of any 'lfbd' lookup, but a 'lfbd' lookup does contain a substitution for that glyph, does the 'lfbd' lookup apply to that glyph? If a glyph at the left end of a line is not in the coverage table of any 'opbd' but _is_ in the coverage table of a 'lfbd' lookup, does the 'lfbd' lookup apply to that glyph?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9106c-ca98-1891-2c00-ace78615994f
* Version Independent ID: 0feefbc8-23a7-5bc8-76dc-0a336a1c7968
* Content: [Registered features, k-o - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko)
* Content Source: [typographydocs/opentype/spec/features_ko.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ko.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
As Adobe registered this feature, they should provide clarification.

**Comment by khaledhosny** [comment]
These three features are some of the unimplemented featured and should be deprecated (they are unimplementable as they go against how OpenType shaping is done in virtually all implementations). I have only ever seen one font that has `opbd` feature (and the values were just garbage) and no implementation that supports them.

**Comment by tiroj** [comment]
These are part of a speculative model of OTL implementation that Adobe envisaged in the early days of OpenType, in which some features referenced other features. It was based on a misunderstanding of the relationship of OTL feature tags to software UI, so the opbd feature would provide the UI for the lower level lfbd and rfbd features. Not sure what the folks at Adobe were smoking at the time.

I agree with Khaled that these features as specified are unimplemented and probably unimplementable in the common OTL implementation model (so like the daffy size feature). opbd should be deprecated. The lfbd and rfbd should either be deprecated or rewritten in a way that makes them implementable.

**Comment by PeterCon** [comment]
I asked Adobe, who registered these features, to investigate this issue.

In the meantime, I've revised the opbd/lfbd/rtbd feature descriptions as part of work for #347 and #601. I'll repeat here the current drafts for these features (including unchanged portions that are relevant for this issue)—note that the revisions address only #347/#601 and do not attempt to address the issue reported here.

**opbd:**
>*Function:* Aligns glyphs by their apparent left or right extents in horizontal setting, or apparent top or bottom extents in vertical setting, replacing the default behavior of aligning glyphs by their origins. Another name for this behavior would be visual justification. The optical edge of a given glyph is only indirectly related to its advance width or bounding box; this feature provides a means for getting true visual alignment.
>
>*Example:* Succeeding lines beginning with T, D and W would shift to the left by varying amounts when the text is left-justified and this feature is applied. Succeeding lines ending with r, h and y would likewise shift to the right by differing degrees when the text is right-justified and this feature is applied.
>
>*Recommended implementation:* <del>Values for affected glyphs are defined with a separate record for left, right, top, and bottom. Each record describes the amount by which the placement and advance width should be altered (GPOS lookup type 1).</del><ins>Positioning adjustments (GPOS lookup type 1) are implemented in separate lookups associated with features for left, right, top and bottom line positions.</ins>
>
>*Application interface:* <del>For GIDs found in the &#39;opbd&#39; coverage table, the application calls one of two related tables, depending on the position of the glyph. For glyphs at the left end of a horizontal line, it calls the [&#39;lfbd&#39;](#lfbd) table, for glyphs at the right end of a horizontal line, it calls the [&#39;rtbd&#39;](features_pt.md#rtbd) table.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. The application implementation for this feature should make use of the [&#39;lfbd&#39;](#lfbd) and [&#39;rtbd&#39;](features_pt.md#rtbd) features: the &#39;lfbd&#39; feature should be applied automatically to glyphs at the left end of a horizontal line; the &#39;rtbd&#39; feature should be applied automatically to glyphs at the right end of a horizontal line. It affects the line length, which should be taken into consideration by line-breaking and justification algorithms.</ins>
>
>*UI suggestion:* This feature should be active by default.<del> It effectively changes the line length, so justification algorithms should account for this adjustment.</del>

**lfbd:**
>*Function:* Aligns glyphs by their apparent left extents at the left ends of horizontal lines of text, replacing the default behavior of aligning glyphs by their origins. This feature is called by the Optical Bounds ([&#39;opbd&#39;](#opbd)) feature.
>
>*Example:* Succeeding lines beginning with T, D and W would shift to the left by varying amounts when the text is left-justified and this feature is applied.
>
>*Recommended implementation:* Values for affected glyphs describe the amount by which the placement and advance width should be altered (GPOS lookup type 1).
>
>*Application interface:* <del>For GIDs found in the &#39;lfbd&#39; coverage table, the application passes a GID to the table and gets back a new XPlacement and XAdvance value.</del><ins>In recommended usage, the application applies this feature automatically to characters at the right end of a horizontal line when the &#39;opbd&#39; feature has been applied to those characters. See the the [&#39;opbd&#39;](#opbd) feature for additional information.</ins>
>
>*UI suggestion:* <del>This feature is called by an application when the user invokes the [&#39;opbd&#39;](#opbd) feature.</del><ins>In recommended usage, this is applied to sequences automatically by applications when the &#39;opbd&#39; feature is used, and direct user control is not required.</ins>

**rtbd:**
>*Function:* Aligns glyphs by their apparent right extents at the right ends of horizontal lines of text, replacing the default behavior of aligning glyphs by their origins. This feature is called by the Optical Bounds [(&#39;opbd&#39;)](features_ko.md#opbd) feature.
>
>*Example:* Succeeding lines ending with r, h and y would shift to the right by differing degrees when the text is right-justified and this feature is applied.
>
>*Recommended implementation:* Values for affected glyphs describe the amount by which the placement and advance width should be altered (GPOS lookup type 1).
>
>*Application interface:* <del>For GIDs found in the &#39;rtbd&#39; coverage table, the application passes a GID to the table and gets back a new XPlacement and XAdvance value.</del><ins>In recommended usage, the application applies this feature automatically to characters at the right end of a horizontal line when the &#39;opbd&#39; feature has been applied to those characters. See the the [&#39;opbd&#39;](#opbd) feature for additional information.</ins>
>
>*UI suggestion:* <del>This feature is called by an application when the user invokes the &#39;opbd&#39; feature.</del><ins>In recommended usage, this feature is applied to sequences automatically by applications when the &#39;opbd&#39; feature is used, and direct user control is not required.</ins>

**Comment by sairuspatel** [comment]
We are investigating.

**Comment by sairuspatel** [comment]
Adobe would like ‘opbd’ and its minions ‘lfbd’ & ‘rtbd’ to be marked as deprecated in the features registry.

**Comment by tiroj** [comment]
I am 100% okay with opbd being deprecated.

The individual lfbd and rtbd features are, however, potentially useful without opbd if rewritten and, indeed, could constitute part of a model that might also involve tpbd (top) and (btbd) bottom optical bounds features for vertical text. The error of the original feature registration was the idea that a single feature was needed to be able to apply the others, as a kind of gateway between application function and the individual features and their lookups. The idea of using GPOS to define margin alignment isn't a terrible one in itself, especially for some scripts and styles that are not well served by algorithmic margin alignment such as currently available in InDesign.

That said, implementation of GPOS optical margin alignment, in both fonts and applications, requires some significant work, which I'm not holding my breath awaiting. I would rather, however, consider these features potential or pending, rather than deprecated. It would be silly to formally deprecate them and then decide down the road that we'd actually like to use them.

**Comment by PeterCon** [comment]
As part of a separate issue that required touching the “Application interface” fields, I’ve drafted a revision for ‘lfbd’ and ‘rtbd’ to say the following:

>In recommended usage, the application applies this feature automatically to characters at the right end of a horizontal line when the &#39;opbd&#39; feature has been applied to those characters. See the the &#39;opbd&#39; feature for additional information.

To allow for usage of ‘lfbd’ or ‘rtbd’ independent of ‘opbd’, I’ve have to revise that, but that would be doable.

**Comment by PeterCon** [comment]
Summarizing some of the history:

-	In 2016 when we created STAT, we decided to have an axis-value format that could provide style-linking information, which could help in particular for existing “B” and “I” user interfaces.
-	In 2016, we independently decided to have an axis-value format that could define ranges, particularly with (non-variable) optical size in mind—though it was never suggested that it could only be used for opsz.
-	The original intent for this guidance… 

“No two tables of the same format should provide information for the same axis value”

was to avoid potential ambiguity. For example, a font could include two axis value tables for the same value but with different name IDs, thereby creating ambiguity. Now, the wording “same axis values” has been read by some to not apply to format 2 and format 3 since they have different fields. However, the original intent was that no two axis value should have the same _value_ or _nominalValue_ for the same axis. (Otherwise, you could get Format2.value == Format3.nominalValue but Format2.nameID != Format3.nameID.)

-	In 2016, we didn’t anticipate any particular need to have axis-value tables that could provide _both_ style-linking _and_ range information.
-	Since then, some font developers have thought it might be useful to provide style-linking _and_ range information for the same axis value, and have added both format 2 and format 3 tables for the same (nominal) value, based on one reading of the current spec.


It seems to me there are three possible options:

1)	Revise the text of the STAT table to clearly sanction having both format 2 and format 3 tables for the same (nominal) value, but indicating they must have the same nameID.

2)	Revise the text to make clear that combining format 2 and format 3 tables should _not_ be done, but define a new format that provides both range and style linking info for a given axis value.

3)	Revise the text to make clear that combining format 2 and format 3 tables should _not_ be done, and _do nothing_ to accommodate providing both range and style linking info for the same axis value.

Re option 2, Adobe provided a draft proposal in the past, but it IIRC it came when most were busy with other matters and so never got much discussion. Sairus’ earlier comment reflects this:

> this hasn’t been a space which folks seem to be very excited about

Also, option 2 would have the issue that it would require software changes to support the new format, which will involve some latency. That shouldn’t stop us, however, if that’s what would be best long term.

Some things that pertain to both option 2 and option 3:

-	On the one hand, the whole style-linking user experience: on the one hand, it the “B” and “I” affordances and associate keyboard shortcuts are ubiquitous. 
-	On the other hand, variable fonts introduce many more variables into the scenario (or, more precisely, many more variable values), which makes it much less clear what a good style-linking UX design should be when variable fonts are involved.

Because of the latter point, it’s not entirely clear what additional information would be needed to make for a good style-linking UX design, with or without involving ranges. That might argue against #2, and maybe even suggest that the Format 3 table isn’t really sufficient even if ranges aren’t used.


I’ve discussed this with Sairus, and he indicated Adobe would be open to any of these options. They (and I) would just like to move it to closure.

Either option 1 or option 3 are relatively easy changes to make in the spec. Neither completely solve style-linking, but at least 3 is explicit about that, as well as sticking to the original intent to avoid ambiguity in tables.

**Comment by tiroj** [comment]
Note that an actual implementation would throw up a number of interesting practical issues. The lfbd and rtbd features should be applied, respectively, when text is left-aligned or right-aligned. That would imply not only margin alignment, but also column alignment, and even tab alignment. While margin and column widths may reasonably be assumed to be wide enough to merit text boundary alignment, tab distances may be close, and it may be necessary for software to use some kind of tolerance when determining whether to apply a boundary alignment feature.

If text is justified (i.e. both left and right boundaries are aligned to margin, column edges, etc..) the output of the lfbd and rtbd features needs to be taken into account for linebreaking and other justification functions such as wordspacing tolerances or kashida insertion.
_____

Because of the amount of work involved in defining lfbd and rtbd GPOS lookups (and the current lack of any very convenient visual editing tool), I don't imagine it being something a lot of font makers would do for a lot of fonts (although that may be different if automated (paging Mr Cozens)). I can imagine it being most desirable in some display fonts with unusual glyph shapes, extending left and right swashes intended for line initial and final use, and similar things that don't submit well to algorithmic text boundary alignment.

**Comment by tiroj** [comment]
[STAT table stuff posted to wrong issue?]

**Comment by khaledhosny** [comment]
> The individual lfbd and rtbd features are, however, potentially useful without opbd if rewritten and, indeed, could constitute part of a model that might also involve tpbd (top) and (btbd) bottom optical bounds features for vertical text.

I still GPOS is a bad place for this information. GPOS arranges lookups in scripts and languages which makes sense while doing basic shaping, but by the time optical alignment is done (after line breaking and after/during justification), the script and language itemization of the text is probably gone, or makes no sense to be respected, but implementations need to still deal with all the complexity or do special casing (e.g. only check for `DFLT` lookups). Moreover, parts of the text layout stack needing this information are not usually OpenType shapers but higher level code, so they are forced to re-implement substantial parts of GPOS table or convince OpenType engines to give them the data.

Since these features are not used and have been used in the past 20 years, they should be deprecated for good and alternative explored based on the needs of implementations, may be a dedicated table like Apple’s [`opbd`](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6opbd.html) table would be a better and more implementable way, may be something entirely different.

Features like `opbd` or `size` give a feeling that people tried to shoehorn anything vaguely related to glyph positioning into GPOS, even if the model of operation is completely different.

**Comment by tiroj** [comment]
Good points, Khaled. As a counterpoint, one could say that optical bounds adjustments are just kerning to the space outside the text. :)

**Comment by PeterCon** [comment]
I've heard input here and also in other contexts (mpeg-otspec list, offline discussion with Apple, MS.) Based on the combined input, I think there's general consensus to let 'opbd' be deprecated, but not to deprecate 'lfbd' and 'rtbd': there's still thinking that they are potentially useful and indication that they are, in fact, supported in some apps.

**Comment by PeterCon** [comment]
Proposed revisions for next version:

**opbd:**

>## Tag: &#39;opbd&#39;<ins> (DEPRECATED)</ins>

**lfbd:**
>*Application interface:* <del>For GIDs found in the &#39;lfbd&#39; coverage table, the application passes a GID to the table and gets back a new XPlacement and XAdvance value.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. In recommended usage, the application applies this feature to characters at the left end of a horizontal line when paragraphs are left or left and right justified.</ins>

**rtbd:**
>*Application interface:* <del>For GIDs found in the &#39;rtbd&#39; coverage table, the application passes a GID to the table and gets back a new XPlacement and XAdvance value.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. In recommended usage, the application applies this feature to characters at the right end of a horizontal line when paragraphs are right or left and right justified.</ins>
