### ISSUE TITLE
“Ancient Hangul” is an exaggeration

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#587]
'ljmo', 'vjmo', and 'tjmo' are “Required for Hangul script when Ancient Hangul writing system is supported.” This presumably refers to any usage of Hangul that [its script development spec](https://docs.microsoft.com/en-us/typography/script-development/hangul) requires these three features for, which is anything for which there isn’t a precomposed syllable block in Unicode. It isn’t right to call this ancient, since characters like U+119E HANGUL JUNGSEONG ARAEA were used until the twentieth century.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9106c-ca98-1891-2c00-ace78615994f
* Version Independent ID: 0feefbc8-23a7-5bc8-76dc-0a336a1c7968
* Content: [Registered features, k-o - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko)
* Content Source: [typographydocs/opentype/spec/features_ko.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ko.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by behdad** [comment]
Agree.

**Comment by PeterCon** [comment]
Looking. The same change would be applied to descriptions for all of 'ljmo', 'vjmo' and 'tjmo'.

**Comment by PeterCon** [comment]
Changed for next version (same edit for 'ljmo', 'tjmo', 'vjmo'):

>*Script/language sensitivity:* Required for Hangul script when <del>Ancient Hangul writing system is supported</del><ins>Unicode conjoining jamo characters are used</ins>.

**Comment by NorbertLindenberg** [comment]
> _Script/language sensitivity:_ Required for Hangul script when ~Ancient Hangul writing system is supported~Unicode conjoining jamo characters are used.

This change seems to contradict a [statement in the Hangul shaping engine documentation](https://docs.microsoft.com/en-us/typography/script-development/hangul#analyze-the-syllables), which limits the use of conjoining jamo to syllables that can’t be represented using precomposed hangul:

> It is important to note that if any of the Jamo sequences being analyzed is capable of forming a Modern Hangul Syllable, the shaping engine does not apply OpenType features to shape them. Composition of Modern Hangul syllables is expected to be done using the pre-composed section (U+AC00 – U+D7AF), as described in the Unicode Standard.

Is that statement wrong?

**Comment by PeterCon** [comment]
Well, if you have a glyph for a precomposed syllable like AC00, then none of the 'ljmo', 'tjmo', 'vjmo' features need to be applied to it.

As for that statement in the shaping engine doc, there's a long saga wrt Hangul. I'll skip all that happened circa 1991 (I wasn't involved then), and start circa 2001: 

There were precomposed syllables, there were conjoining jamo, and there were decomposition mappings from the former to sequences of the latter. Sounds reasonable. Except... It turns out that the precomposed syllables were sufficient for typical modern (late 20th century) usage, but incomplete for representing older texts. So, older texts required use of jamo sequences. 

That's probably familiar.

*But the problem was worse than that:* The set of jamo characters added in Unicode 1.1 were incomplete. There are a complete set of singleton L jamos, V jamos, and T jamos; and there are some L, V and T jamo pair or triple combinations. But the sets of pairs/triples were not sufficient for representing Hangul texts. As a result, circa 2001, if you wanted to encode older texts, you would end up needed to encode sequences that would include two or three L jamos, e.g., <1103, 1106...>.

So, circa 2001, Microsoft implements support for Old Hangul with fonts that shipped as an Office XP add-on in Korea. And that's when the first revision of the Hangul shaping doc'n is created.  And it includes tables of the L jamo combinations that needed to be supported and ligated using 'ccmp'; and likewise for V and T combinations.

Move forward to circa 2004/2005: I've started working on shaping engines. For some reason, Hangul comes up, and I learn about the above details and what's been spec'd / implemented. But I'm also familiar with details of Unicode normalization.

Ah, normalization. The precomposed syllables decompose, and can be recomposed. So, suppose you have a sequence

`1103 1106 1161`

When this undergoes NFC normalization, it becomes this:

`1103 B9C8`

In Microsoft's implementation at the time, that NFC representation would not display as a conjoined syllable the same as the NDF representation. So, I say, "That's a bad bug!" And I proceed to spec a design change for Uniscribe that would allow both representations to display the same, as you'd expect them to.

Now we come forward to circa 2005/2006, around when Windows Vista shipped—with the revised Hangul engine. (Windows still didn't ship with an Old Hangul font.) If you had documents that used only precomposed syllables *or* sequences like `1103 1106 1161`, they'd display the same. **But,** previously if you tried to use a sequence like `1103 B9C8` it wouldn't work, whereas now it *would* work. I thought of that as a bug fix. But it turned out that people in the Korean standard organization considered that a *breaking change*.

You see, the intent of the Korean standards organization was that documents should only be encoded with syllables represented in one of the following patterns:

* S (precomposed syllable)
* L + V (single choseong + single jungseong)
* L + V + T (single choseong + single jungseong + single jongseong)

But the problem was that, back in 1990, they somehow overlooked that the sets of L, V and T jamos that were encoded were incomplete: they were missing a bunch of pair/triple combinations needed in older texts.

So, I find myself engaging with someone from MS Korea explaining Unicode normalization and the repertoire of syllables required for older Hangul texts. I'm getting explained to me that sequences like LLV... (multi-L, multi-V or multi-T), or worse, LS and LST, were anathema from the Korean standards organization.

OK, now we skip ahead to 2008. The ROK standards organization publishes KS X 1026-1:2007 *Information Technology - Universal Multiple Octet Coded Character Set - Hangul - Part 1: Hangul processing guide for information interchange*. This standard stipulates that only the three patterns above are valid. In particular, it states,

>In addition, we must adhere to the following rules when representing in Johab Hangul syllable blocks.
>
> 1) ... two or more code positions of simple letters cannot be concatenated to represent a single complex letter...
> 2) A Wanseong syllable block cannot be recomposed with Johab Hangul letter(s) to represent another Hangul syllable block.<br>- an example. &#xac00;&#x200b;&#x11eb; (U+AC00 U+11EB, incorrect) &#x21d2; &#x1101;&#x1161;&#x11eb; (U+1101 U+1161 U+11EB, correct)

And, in parallel, the ROK standards organization proposes the [Hangul Jamo Extended-A, A960..A97F](http://www.unicode.org/charts/PDF/UA960.pdf) and [Hangul Jamo Extended-B, D7B0..D7FF](http://www.unicode.org/charts/PDF/UD7B0.pdf) blocks to complete the set of two- and three-part L, V and T jamos that they should have proposed back in 1990.

So, those blocks get added in Unicode 5.2. By that time Microsoft is working on Windows 8. And now we have this ROK standard our MS Korea people are telling us to implement. So, we end up with the third revision of the Hangul engine and specs.

Note that conforming to KS X 1026-1 means that you're not treating canonically-equivalent sequences the same.

Skip ahead several years—maybe 2015, I forget exactly when. No other platform (including Samsung Android devices) is conforming to KS X 1026-1 and deviating from Unicode. And it's been several years since we heard anything from Korea regarding Old Hangul. But, Edge is competing with other browsers, and they start getting bugs that they are not displaying Old Hangul texts the same as in other browsers: some sequences (e.g., LS) don't conjoin as in other browsers. So, the Windows 8 changes get reverted.

Thus, Microsoft's Hangul shaping engine has gone through at at least 4 revisions that I'm aware of. I don't think I was directly involved in the last revision (I certainly didn't spec anything). And at this point, I've lost track of what assumptions are reflected in the published [Hangul script development](https://docs.microsoft.com/en-us/typography/script-development/hangul). The statement you quoted,

> if any of the Jamo sequences being analyzed is capable of forming a Modern Hangul Syllable, the shaping engine does not apply OpenType features to shape them. Composition of Modern Hangul syllables is expected to be done using the pre-composed section (U+AC00 – U+D7AF)

*seems* to reflect the KS X 1026-1 conformance requirements. But doesn't mention the new extended jamo blocks at all. So maybe that's a statement that goes back to circa 2001.

**Comment by NorbertLindenberg** [comment]
Interesting story, but what does it mean for OpenType rendering systems today? How should they handle the sequence U+1100 “ᄀ” U+1175 “ᅵ” U+11B7 “ᆷ”? It’s canonically equivalent to U+AE40 “김”. According to your new statement, `ljmo`, `tjmo`, and `vjmo` should be applied because it’s a conjoining jamo sequence. According to the Hangul shaping engine description, no OpenType shaping features (not even `ccmp`!) are applied because it can be represented as a modern Hangul syllable.

Of course this also relates to our discussion about cmap and Unicode normalization in #591.

**Comment by PeterCon** [comment]
Is the question about what a rendering engine should to, or about what data a font should include? Or both?

Given a string with character sequence <1100, 1175, 11B7>, a rendering engine might do one of two things:

1) Shape that character sequence:
  1.1 Do 'cmap' entry lookup to get default glyphs for 1100, 1175, 11B7
  1.2 Process 'ccmp' lookups on that glyph sequence
  1.3 Process 'ljmo', 'vjmo', 'tjmo' lookups on that glyph sequence (or it might apply each of those only to the corresponding jamo characters)
2) Compose the character sequence into the precomposed syllable AE40 and then shape that
  2.1 Do 'cmap' entry lookup to get default glyph for AE40

For implementation 1, a font doesn't need to have any 'ccmp' lookups to compose multi-part L, V or T jamos, but it could use 'ccmp' lookups to ligate L, V T glyph sequences into a syllable ligature glyph (same glyph would be the cmap default for AE40). Otherwise, the 'ljmo', 'vjmo' and 'tjmo' lookups make appropriate substitutions (with or without contextual variants).

For implementation 2, there's no need for 'ccmp', 'ljmo', 'vjmo' or 'tjmo' to be applied to a precomposed syllable character.

For a rendering implementation, I think the choice between 1 and 2 *could* be made optional: any Hangul font is going to (or definitely should) include atomic glyphs for any of the precomposed syllable characters, and as those glyphs were designed as complete syllables by the font designer, the rendering will be at least as good or better than a shaped composition. But in that case the guidance to a font developer should be that they should anticipate rendering engines that use implementation 1. 

>According to the Hangul shaping engine description, no OpenType shaping features (not even ccmp!) are applied because it can be represented as a modern Hangul syllable.

Well, that's where my story comes in: that spec is evidently assuming a ROK standards point of view, that jamo sequences like <1100, 1175, 11B7> *should never occur in documents*. Personally, I don't think that should be assumed (in spite of KS X 1026-1), and so I think the Hangul shaping spec needs a major revision.

**Comment by NorbertLindenberg** [comment]
I disagree with the statement that “any Hangul font is going to (or definitely should) include atomic glyphs for any of the precomposed syllable characters”. Over the last few decades, “out-of-frame” designs, where syllables don’t have to be fitted into the same fixed size frame, have become quite popular for Hangul (for examples, see [Ahn Sang Soo and AG Typography Institute](https://letterformarchive.org/news/from-the-collection-ahn-sang-soo)).

For such designs, it would be more natural to start with jamo and apply some substitutions and positioning, rather than work with complete syllables.

**Comment by PeterCon** [comment]
>For such designs, it would be more natural to start with jamo and apply some substitutions and positioning, rather than work with complete syllables.

Interesting. It sounds like you're suggesting either that ccmp, ljmo, vjmo and tjmo always be applied to precomposed syllables, or else that a way be provided for the font developer to signal to a shaping engine that precomposed syllables should be decomposed and ljmo, vjmo, tjmo be applied to the jamo sequences. My guess is you have the former in mind?

**Comment by behdad** [comment]
> Interesting. It sounds like you're suggesting either that ccmp, ljmo, vjmo and tjmo always be applied to precomposed syllables, or else that a way be provided for the font developer to signal to a shaping engine that precomposed syllables should be decomposed and ljmo, vjmo, tjmo be applied to the jamo sequences. My guess is you have the former in mind?

What the Hangul shaper does is the following pre-processing of the Unicode text, before OT Layout is engaged:
- Identify each Hangul syllable,
- For each syllable, if a fully-composed Unicode character exists and the font supports that in cmap, then use that pre-composed character,
- Otherwise, fully decompose the syllable.

That's all. ccmp, ljmo, vjmo, tjmo features are globally applied.

If a font designer wants to decompose precomposed Hangul syllables, they can and already do that in GSUB.

**Comment by PeterCon** [comment]
Since these are not for discretionary typographic behaviours but are part of the required implementation for a particular script, the feature descriptions should really go hand-in-hand with a shaping specification. The features were registered by Microsoft, and my current draft is consistent with their Hangul shaping specification. I'm open to revising the feature descriptions subject to their review. (I'd do likewise for features registered by anybody else.)

Note: the original intent of "open" in "OpenType" was that different vendors could register features that would be used in their own applications, or that could be adopted for use in other applications. See <https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1>: 

>The OpenType Layout feature model provides great flexibility to font developers because features do not have to be predefined by Microsoft Corporation. Instead, font developers can work with application developers to determine useful features for fonts, add such features to OpenType Layout fonts, and enable client applications to support such features.

Now, taken in that way, this suggests that different app vendors could come up with different features for nearly the same purpose, which would NOT be helpful in a different goal of "OpenType fonts just work" (<https://docs.microsoft.com/en-us/typography/opentype/spec/overview>). But lack of cross-vendor shaping specs has been a gap since it was first called out back in 1997. That's not satisfactory at all.

So, I'm very much in favour of moving toward convergence on one shaping spec for Hangul (or any other script). In this case, if both Harfbuzz and CoreText have (more or less) the same behaviour for Hangul, then I'd push for getting Microsoft on board with that design, and it could begin by revising these feature descriptions accordingly.
