### ISSUE TITLE
Make clear how glyph bounds should be calculated 

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#598]
In various places in the spec, the bounding box (glyf: min/max/X/Y, hhea: LSB, head: x/y/MinMax, hhea: xMaxExtent …) is needed. But it doesn't say how to measure it. If by coordinates of the nodes or from the ink box. This makes a difference with missing extreme points. 
It would be nice to have a note about that or have a central place where it is expanded in detail and having links to it in the relevant places.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b569bf16-eea2-0953-3345-024bbd9bd8d4
* Version Independent ID: 5e1b6957-a7c9-fef1-5928-dca56d848565
* Content: [hmtx - Horizontal metrix table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/hmtx)
* Content Source: [typographydocs/opentype/spec/hmtx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/hmtx.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by tiroj** [comment]
It would be a good idea to compare notes with Apple on this topic, to confirm that the method defined for quadratic outlines in OT is the same as they recommend for TT. Calculation of bounding box came up in passing when I was speaking with Peter Lofting recently.

**Comment by PeterCon** [comment]
OT spec glyf chapter currently says:

>Note that the bounding rectangle from each character is defined as the rectangle with a lower left corner of (xMin, yMin) and an upper right corner of (xMax, yMax).

That states how the bounding box is defined in terms of xMin, etc., but doesn't state how those values should be set.

Apple's glyf spec currently says:

>The minimum and maximum x and y values for the coordinate data in the glyph follow and together define the glyph's bounding box. This is the bounding box for the original glyph outline before any grid-fitting has taken place.

That wording *seems* suggest that the values are determined from point coordinates, whether on- or off-curve.

**Comment by tiroj** [comment]
The use of the term 'coordinate data' does imply that the values are determined from _point_ coordinates. I suspect what Georg is wondering is what should be done when calculating the bounding box for a glyph that lacks on-curve points at extrema, where either the part of the glyph shape itself may be beyond the bounding box as defined by point coordinates or off-curve points may be defining the bounding box beyond the glyph shape.

Historically, one would have said such glyphs were poorly constructed, because recommendations were always that outlines should have on-curve points at extrema. But that recommendation — in both TTF and PS/CFF — was tied up in the hinting model, which needed points/nodes at extrema in order to be able to apply stem hints or alignment links to bowls. It isn't clear to what degree such recommendations remain pertinent if hinting isn't part of the picture (as it hasn't been in most Apple rendering for a couple of decades). When I was talking with Peter Lofting recently, something he said implied that bounding box should perhaps be calculated from ink, i.e. from the outline shape rather than from point coordinates.

**Comment by behdad** [comment]
All bounding boxes in the spec should be calculated as min/max x/y of the outline points (on-curve and off-curve; also known as the control-box). The true ink bounding box is never used.

For `glyf` table, those are always integer. For CFF/CFF2, non-integer coordinates are possible. For that, the min values should be rounded down and max values rounded up when encoding in other tables that take an integer. Note that even though the LSB of CFF/CFF2 glyphs is encoded in the `hmtx` table, unlike with `glyf` table, changing the encoded LSB in `hmtx` does *not* move the glyph around. The LSB value is irrelevant there.

**Comment by PeterCon** [comment]
Proposed draft for the next version: Add clarification in the 'glyf' chapter, Glyph header section:

>Note that the bounding rectangle from each character is defined as the rectangle with a lower left corner of (xMin, yMin) and an upper right corner of (xMax, yMax).<ins> These values are obtained directly from the point coordinate data for the glyph, comparing all on-curve and off-curve points. It does not require computing the outline to determine if there are extrema outside these limits. Phantom points computed by the rasterizer are not relevant.</ins>

Looked elsewhere for references to "bounding" box to see if cross-reference to 'glyf' should be added. Made small changes for that in HVAR and VVAR chapters.

**Comment by schriftgestalt** [comment]
Thanks

**Comment by behdad** [comment]
> It does not require computing the outline to determine if there are extrema outside these limits.

This is wrong. Because bezier curves are convex functions, the true curve limit never can fall outside the control-box limits. It can fall (strictly) inside though. That is why these bounds are sufficient: they are guaranteed to include the full ink.

**Comment by PeterCon** [comment]
??

What you've said implies that

>It does not require...

is correct. Am I misunderstanding something?

**Comment by behdad** [comment]
> is correct. Am I misunderstanding something?

Your statement implies that true bounds might go outside control-box bounds. I'm saying mathematically they never can.

**Comment by behdad** [comment]
The key word I'm objecting to is "outside" in your wording.

**Comment by PeterCon** [comment]
Got it. Revised draft:

>Note that the bounding rectangle from each character is defined as the rectangle with a lower left corner of (xMin, yMin) and an upper right corner of (xMax, yMax).<ins> These values are obtained directly from the point coordinate data for the glyph, comparing all on-curve and off-curve points. It is not required to compute the outline to determine extrema. Phantom points computed by the rasterizer are not relevant.</ins>

**Comment by behdad** [comment]
> It is not required to compute the outline to determine extrema.

This suggests that an over-eager implementation might do that. Since we are a file format spec, we should aim to be clear as to what needs to be done.

If I was to word this section, I'd say something like "the control-box bounding-box is not necessarily tight to the curve."

**Comment by tiroj** [comment]
Since there has been confusion about this among font tool makers, maybe we should explicitly state somewhere that ‘the bounding box is the bounded area defined by point coordinates, not by the outline shape of the glyph'?

**Comment by vlevantovsky** [comment]
I believe it's been a recommended practice (at least since the TTF days) to always have an on-curve control point placed at the extrema of the outline, which makes perfect sense - makes hinting / grid-fitting work easier, and the bounding box of the outline can be easily computed as [min, max] values of on-curve point coordinates. For this reason, the outline bounding box has often been considered an "ink bounding box", where non-overlapping bounding boxes would guarantee that rendered glyphs do not ever have ink collision.
However, if the control points are  placed arbitrary and are not located at the extrema points - the ink bounding box can only be determined by computing the outline. If we were to redefine the meaning of the bounding box, maybe we should consider the purpose of the bounding box in the first place, before the changes are discussed and/or made.

**Comment by tiroj** [comment]
>  to always have an on-curve control point placed at the extrema of the outline, which makes perfect sense

Except when it doesn't make perfect sense, e.g. at the extrema of short curve segments at the tip of serifs.

I don't think we're talking about redefining the meaning of bounding box, only clarifying the existing specification—which refers to point coordinates, _not_ to ink—to make clear that 'often been considered an "ink bounding box"' is incorrect, and is only an accident of recommendations for making fonts that mostly had to do with hinting. As Behdad points out, non-overlapping bounding boxes still guarantees that rendered glyphs to not ever have ink collision, because the curves are convex functions, so the extreme point coordinates are always on or outside the ink.

**Comment by tiroj** [comment]
Illustration: cubic and quadratic serif construction with short curve segment tips. These features are so small that adding on curve points to the extrema would distort the curve. Omitting extrema nodes in this situation has been an accepted exception to the general rule for PS/CFF outlines since Type 1 days; when such outlines are converted to TTF quadratic curves, they typically end up with a singe off-curve point defining the curve. In both formats, this results in a bounding box that is larger slightly than the ink.
<img width="343" alt="Screenshot 2020-09-11 at 10 28 42 AM" src="https://user-images.githubusercontent.com/5614500/92955501-1bbe3a00-f41a-11ea-9d2e-2c7760190c33.png">

**Comment by PeterCon** [comment]
Revised draft based on feedback:

>Note that the bounding rectangle from each character is defined as the rectangle with a lower left corner of (xMin, yMin) and an upper right corner of (xMax, yMax).<ins> These values are obtained directly from the point coordinate data for the glyph, comparing all on-curve and off-curve points. Phantom points computed by the rasterizer are not relevant. Note that the bounding box defined by control points is guaranteed to contain the outline, but might not be tight to the outline.</ins>

**Comment by behdad** [comment]
Great. THanks.
