### ISSUE TITLE
[recom post] Obsolete guidance re glyph names

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#608]
The 'post' section states:

>Note that names for all glyphs must be supplied as it cannot be assumed that all Microsoft platforms will support the default names supplied on the Macintosh.

Is this obsolete guidance that can be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/recom)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by tiroj** [comment]
It's still possible to make a post table according to Apple's old spec, omitting standard Mac glyph names. I would say something like 'OpenType fonts should either provide glyph names for all glyphs or none (format 3)', without going into the reasons why this differs from the Apple TT spec.

**Comment by khaledhosny** [comment]
> either provide glyph names for all glyphs or none (format 3)

Version 2 post table also allows partial coverage (not all glyphs has name), doesn’t it?

**Comment by PeterCon** [comment]
'post' v2 requires an index into some name data for every glyph in the font, but multiple GIDs can use index 0, which means ".notdef".

**Comment by khaledhosny** [comment]
I’m sure I have seen fonts where some glyphs did not have names (otherwise the possibility wouldn’t have occurred to me). 

The table has `numGlyphs` glyphs that _should_ but not required to be the same as `numGlyphs` in `maxp` table, so it is quite possible to have `numGlyphs` that is less than the number of glyphs in the font and not have any entries for the top glyph IDs.

I modified FontTools to allow me to generate such a font, and it seems to be functional so far. FontBook complains about the `post` table being unusable but otherwise allows me to install and use it. FreeType gives `.notdef` for the glyphs with missing names, but HarfBuzz just synthesizes names for them. I didn’t do more testing, though. But probably the spec needs to use a stronger word than should if this is not supposed to be possible.

**Comment by PeterCon** [comment]
Apple's spec says

>Note that the numberOfGlyphs field must be equal to the numGlyphs field of the 'maxp' (Maximum Profile) table.

But you're right, the OT spec says

>Number of glyphs (this should be the same as numGlyphs in 'maxp' table).

I'm not too surprised that things pretty much work. ("We don't need no stinkin' glyph names!")

>But probably the spec needs to use a stronger word than should if this is not supposed to be possible.

I'm not going to push for that. Hey, I was just wondering if we need to keep that odd-sounding bit about default names supplied by the Mac.

**Comment by khaledhosny** [comment]
In my view glyph names are optional and mostly a debugging information, any tool that depend on them is broken by design. That is a different issue that what is being raised here, sorry for hijacking it.

**Comment by PeterCon** [comment]
Proposed change for the next version, along the lines suggested by John:

><del>Note that names for all glyphs must be supplied as it cannot be assumed that all Microsoft platforms will support the default names supplied on the Macintosh.</del><ins>Some applications might not implicitly support standard Macintosh glyph names. Any glyph names should be provided explicitly in the font.</ins>
