### ISSUE TITLE
[name, cmap] Disentangle name and cmap table specifications

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#615]
The cmap table specification currently refers to the name table specification for some (but not all) information on the platform and encoding IDs. This includes quite a bit of information that’s only relevant for cmap tables.

I suggest disentangling the two specifications by copying most information needed for cmap into the cmap table specification, and deleting all information from the name table specification that's not needed for name tables. I’m making an exception for the Macintosh platform information as it would be identical in the specifications of both tables, and it won’t be needed in the future. I’m using NAME to refer to the name table specification, and CMAP for the cmap table specification.

* Delete the paragraph starting wth “Complete details on platform IDs and platform-specific encoding and language IDs“ from CMAP.

* Copy the section “Platform IDs” from NAME to CMAP. In both copies, identify platform ID 4 as deprecated. In NAME, add a paragraph “Platform IDs 2 and 4 were never intended for name tables.”

* Transfer information from the section “Platform-specific encoding and language IDs: Unicode platform” from NAME to CMAP as described [here](https://github.com/MicrosoftDocs/typography-issues/issues/269#issuecomment-690846238_).

* Edit that section in NAME:
    * Remove the references to cmap subtables from the table.
    * Reduce the first paragraph after the table to “Encoding IDs 0, 1 and 2 are deprecated.”
    * Delete the second paragraph.
    * Reduce the third paragraph to “Unicode platform encoding ID 5 is not used in the 'name' table.”

* In the section “Macintosh platform” of CMAP, add a paragraph: “Information on additional encoding and language IDs that may be encountered in existing fonts is provided in the 'name' table chapter.”

* Move the section “Platform-specific encoding and language IDs: ISO platform” from NAME to CMAP, deleting it from NAME. In CMAP, delete the paragraph after the table.

* Move the section “Platform-specific encoding and language IDs: Custom platform” from NAME to CMAP, deleting it from NAME. In CMAP, delete the second sentence of the first paragraph after the table, and delete the second paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**

**Comment by PeterCon** [comment]
I've attempted to rationalize the coverage of platform/encoding/language IDs in cmap and name chapters. In the proposed draft, the name chapter only includes details relevant to the name table.

Note: These drafts incorporate changes for other issues. Since the overall changes are large, I've provided PDFs for the entire chapters, each in two versions: one showing changes and one with the resulting draft.

[cmap_184_draft_201006.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5337263/cmap_184_draft_201006.pdf)
[cmap_draft_201006_delta-from-183.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5337264/cmap_draft_201006_delta-from-183.pdf)

[name_184_draft_201006.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5337265/name_184_draft_201006.pdf)
[name_draft_201006_delta-from-183.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5337266/name_draft_201006_delta-from-183.pdf)
