### ISSUE TITLE
Hi I would like to suggest a new OT feature tag. Where should I submit it to?

### ISSUE THREAD

**Issue by avrahamcornfeld** [MicrosoftDocs/typography-issues#641]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 844c49c1-bbee-b298-f6da-ace893d4e52b
* Version Independent ID: c8880433-22b5-a615-586f-fee121d096fd
* Content: [Feature tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/featuretags)
* Content Source: [typographydocs/opentype/spec/featuretags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/featuretags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by davelab6** [comment]
This is a good place :)

**Comment by avrahamcornfeld** [comment]
Hi Dave,
In Hebrew we need a feature for words that are meant for all genders. 
https://en.wikipedia.org/wiki/Grammatical_gender
Examples: דרושים/ות דרוש/ה א.נשים
These are words that have a slash or period as part of the word so that it is meant for male and female. 
Recently there are some projects aimed to make this more aesthetic, for instance: https://www.facebook.com/MultiGenderHebrew/
I've been using the TITL feature tag since it is rarely used, but would be better to have a GNDR tag for better semantics.
Thanks
Avraham ◔‿◔

**Comment by PeterConstable** [comment]
@avrahamcornfeld Rather than describing a context of usage, I think it would be helpful to focus on the typographic effect that's involved: what should change typographically? (Perhaps there are other contexts in which the same change would be appropriate.)

If you look at the [feature registry](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae), you'll see that all the feature descriptions have a common template of fields. It might be helpful if you drafted text for "Function" and "Example" fields for your proposed feature: I think that would help focus discussion.

**Comment by tiroj** [comment]
Based on my understanding of the graphical examples shown at 
https://www.facebook.com/MultiGenderHebrew/
I would say this is not suitable to be a glyph-level substitution for the slash character, since the slash glyph is entirely removed from the glyph string and replaced by special handling of adjacent letter display. It would be better if this could be unambiguously encoded in some way without treating the slash as a kind of formatting control consumed in the glyph display.

**Comment by avrahamcornfeld** [comment]
Here are some other examples
Before:
![image](https://user-images.githubusercontent.com/18214595/95296730-f76f4500-0881-11eb-828d-dc3022d9a5e1.png)
After:
![image](https://user-images.githubusercontent.com/18214595/95296666-d870b300-0881-11eb-8cc4-06db783145b2.png)

The slash is sometimes part of the feature. The feature icludes both alternates and ligatures.

**Comment by tiroj** [comment]
I understand the idea. The purpose of registering a specific OTL feature is to enable interoperability between fonts and access to features via document creation tools (e.g. software UI or styling markup). Innovative ideas for features that are not already well-established in typography are not always obvious candidates for standardisation, because it isn't clear how widely adopted they are likely to be, what alternative methods addressing the same goal might exist or emerge, or how the method might be generalised (i.e. not be Hebrew-specific or not linked to using / as the format control character).

I second Peter's suggestion that you draft a proposed feature description following the template, so we can talk this through in more detail.

**Comment by PeterCon** [comment]
@avrahamcornfeld : Unless a proposed feature description (following the template) is provided, or at least a start with the function and example fields, then this won't really be actionable and the issue will be closed.

**Comment by PeterCon** [comment]
Closing this since information needed to move forward hasn't been provided. Please feel free to re-open or to create a new issue for a proposal with specific details.
