### ISSUE TITLE
Is it possible to change the scaling of the Microsoft Himalaya font so it is actually readable without having to use it at 22pt? This would be very helpful for bilingual docs. TIA

### ISSUE THREAD

**Issue by angelakyle** [MicrosoftDocs/typography-issues#642]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c67afc2-0e22-0380-9555-dc226af7f748
* Version Independent ID: 275be3ea-0e35-5749-7e59-7b298ba08ddb
* Content: [Microsoft Himalaya - Typography](https://docs.microsoft.com/en-us/typography/font-list/microsoft-himalaya)
* Content Source: [typographydocs/font-list/microsoft-himalaya.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/microsoft-himalaya.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
I can anticipate the answer to this fro Microsoft. No, it isn't possible to change the scaling of a shipping fonts, especially not one that has been part of the OS for as long as Microsoft Himalaya, because this would affect all existing documents using the font. As a general principle, when I am working on fonts for Microsoft, I am not allowed to make changes that would result in reflow of existing documents.

The Microsoft Himalaya font is scaled 'small on the body' in order to ensure that syllabic stacks can fit within the same vertical metrics as Latin fonts that are used in software UI. This is also why stacks are composed of contextually shortened forms, so that as stacks get longer they do not grow too tall. This is a compromise of the traditional proportions of the script for a technical purpose (similar or even worse compromises are applied to other writing systems to get them to fit within UI metrics). Because Microsoft Himalaya is the default and fallback font for Tibetan script in Windows, it needs to work in this constrained way.

Microsoft could ship another version of the font under a different name, with both changed scale and less squished stacking forms. I think this would be worthwhile, but I've not discussed it with anyone at Microsoft.

**Comment by angelakyle** [comment]
Another version would be very helpful. There aren't default options for Tibetan script and as is, the readability is very poor.

**Comment by PeterConstable** [comment]
The small sizes of Himalaya and certain other fonts is an issue I started mentioning around when Windows Vista shipped. (Vista was the first version that included Himalaya. A problem for the first font in Windows that supports a given script is that it ends up getting used in user interfaces (typically as a fallback font). So, open up File Explorer, create a new file and rename it using a Tibetan string: that file name in File Explorer will be displayed using Himalaya. And the presentation of the string needs to fit into the text control used to create the UI, and that text control has a fixed size, optimized for the primary UI language (or, quite possibly, optimized for the first-authored UI language, English, without any adjustment during localization for other UI languages). If the scaling of Himalaya glyphs was set to an appropriate size for document use, then undoubtedly most Tibetan strings in UI contexts would get clipped top and bottom making them not fully legible.

**Comment by angelakyle** [comment]
I get it, there are specific technical reasons that make fixing this issue difficult, perhaps impossible in some opinions. However, Tibetan is a living language--one that is struggling to persevere. The fact that reasons can be given which effectively derail the ability to use a living language on screen speaks to enormous cultural privilege.

**Comment by PeterConstable** [comment]
>The fact that reasons can be given which effectively derail the ability to use a living language on screen speaks to enormous cultural privilege.

@angelakyle : I hope my comments didn't come across as suggesting there should be any cultural privilege because my intent was quite the opposite: I thought it was bad that Tibetan strings within an English UI were illegibly small, and I tried to suggest some ways it might be overcome, such as allowing text to bleed outside a text control (perhaps limited by default, but full bleed when the mouse cursor is hovered over, or the control is in focus).

**Comment by angelakyle** [comment]
Thank you. The options you suggested would be better than what is currently implemented.
