### ISSUE TITLE
Ambiguous language system tag: 'IJO '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#66]
'IJO ' is called “Ijo languages” but is mapped to the ISO 639 code ijc, which is the individual language Ijo/Izon. The plural name implies that it should be mapped to ijo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It was originally described as "Ijo". When the mappings to ISO 639 were added in OT 1.6, ijc was chosen to reflect the most-likely language. 

In OT 1.7, the description was changed to "Ijo languages"; I don't know what prompted that change. When that change was made, however, no change was made to the ISO 639 mapping info -- a clear oversight.

Will be fixed in the next version.
