### ISSUE TITLE
fsType embedding values?

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#699]
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fstype

I found myself pondering today why the fsType field in the OS/2 table is spec'd the way it is: in particular, why the embedding bit values are defined in as sub-field values 0, 2, 4, 8 instead of just directly defined in terms of the bits 0, 1, 2, 3?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/os2)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
The documentation was re-organized that way in 1.8.3 because bits 0 - 3 are a set, distinct from other bits in purpose and in rules for validity. In particular, bits 0 - 3 are mutually exclusive, and so only sub-field values 0, 2, 4 or 8 are valid. 

Does making it a subfield help make that clearer? The same as in 1.8.2?

**Comment by PeterCon** [comment]
No further comments were received suggesting a need for revision to the 1.8.4 content, so closing.
