### ISSUE TITLE
There is an error in “Format 4: Segment mapping to delta values”

### ISSUE THREAD

**Issue by Simakeng** [MicrosoftDocs/typography-issues#77]
The description of "searchRange" indicates that this value should equal to  "2 × (2**floor(log2(segCount)))", but under this form is a example, it used a different formular.("64 (= 2 × largest power of 2 &lt;=39)").
    After search, I found the same error in ISO documentation too.(ISO/IEC 14496-22:2015,Page 13)
    I opened a OTF font find that the value of "searchRange" actually is calculated via the formular in the Description.
    I hope someone can fix this problem, It may cause a lot of confuse to developers.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/zh-cn/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Isn't the example simply expressing the same formula in prose? (The expression 2**floor(log2(segCount)) is equivalent to "the largest power of 2 that is less than or equal to segCount.) Can you clarify what is incorrect, or what will cause confusion?

**Comment by PeterCon** [comment]
Note: the specification for searchRange and the example provided have been this way for a long time, and match what is in Apple's TrueType specification:

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html

**Comment by Simakeng** [comment]
In my understanding, "**" is not means power. So I think of it as a "×", that's why I think it is wrong.
I think it might be better to change that symbol to "^".
Great thank for your reply, and sorry for disturbing you.

**Comment by PeterCon** [comment]
The notation "**" was used in several older programming languages (e.g., Algol, Forth, Fortran) as the exponentiation operator. The 'cmap' table spec was originally written over 25 years ago, in a time frame when those languages would have been more familiar. You bring up a valid point that people today may not be familiar. Perhaps in the next version of the spec this can be modernized or made more generally recognizable.

2 × (2^floor(log2(segCount)))
or
2 × (pow(floor(log2(segCount)), 2))

**Comment by PeterCon** [comment]
Need to reconsider this feedback to provide better clarity for all readers of the spec.

**Comment by PeterCon** [comment]
While fixing this, should make parallel changes for similar fields in otff.htm.

**Comment by PeterCon** [comment]
Changed for next version:

><table>
<tr><td>uint16</td><td>searchRange </td><td> <del>2 × (2**floor(log2(segCount)))</del><ins>Maximum power of 2 less than or equal to segCount, times 2 ((2&ast;&ast;floor(log<sub>2</sub>(segCount))) * 2, where “&ast;&ast;” is an exponentiation operator)</ins> </td></tr>
<tr><td>uint16 </td><td>entrySelector </td><td><del>log2(searchRange/2)</del><ins>Log<sub>2</sub> of the maximum power of 2 less than or equal to numTables (log<sub>2</sub>(searchRange/2), which is equal to floor(log<sub>2</sub>(numTables)))</ins> </td></tr>
<tr><td>uint16 </td><td>rangeShift </td><td><del>2 × segCount - searchRange</del><ins>segCount times 2, minus searchRange ((segCount * 2) - searchRange)</ins> </td></tr>  
</table>

<ins>To assist in quick binary searches, the searchRange, entrySelector and rangeShift fields are included as parameters that may be used in configuring search algorithms. In particular, binary search is optimal when the number of entries as a power of two. The searchRange field provides the largest number of items that can be searched with that constraint (maximum power of two). The rangeShift field provides the remaining number of items that would also need to be searched. The entrySelector field indicates the maximum number of levels into the binary tree will need to be entered.</ins>

<ins>In early implementations on devices with limited hardware capabilities, optimizations provided by the searchRange, entrySelector and rangeShift fields were of high importance. They have less importance on modern devices, but may still be used in some implementations. However, incorrect values could potentially be used as an attack vector against some implementations. Since these values can be derived from the numTables field when the file is parsed, it is strongly recommended that parsing implementations not rely on the searchRange, entrySelector and rangeShift fields in the font but derive them independently from numTables. Font files, however, should continue to provide valid values for these fields to maintain compability with all existing implementations.</ins>
