### ISSUE TITLE
Forming RA HALANT blbf KA in Kannada

### ISSUE THREAD

**Issue by N-Anbarasan** [MicrosoftDocs/typography-issues#809]
[Enter feedback here]
I am not able to form RA HALANT blbf KA.
ie RA HALANTwith below base form of KA like in park, work etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a45c60d-a4ca-02dd-3f46-745d7ced8692
* Version Independent ID: 4f14f132-6643-0ee7-c610-76db1b9404ab
* Content: [Developing OpenType Fonts for Kannada Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/kannada)
* Content Source: [typographydocs/script-development/kannada.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/kannada.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
As per the[ Unicode Standard](https://www.unicode.org/versions/Unicode13.0.0/ch12.pdf), the default shaping for Ra+virama+Ka will be the reph form following Ka. To get the subscript form of Ka below the base Ra, you need to insert a ZWJ (U+200D) character _before_  the virama:
![image](https://user-images.githubusercontent.com/5614500/128118859-d9c8384b-7d11-499b-b58c-f2d791dc9e87.png)

**Comment by N-Anbarasan** [comment]
Hi,

Thanks for the info. I wanted to produce the following form
[image: image.png]

**Comment by N-Anbarasan** [comment]
![Ra Halant Ka Owattu](https://user-images.githubusercontent.com/88365451/128182364-19d6b589-d2a1-47f5-be44-2a4346ddd74c.png)
image for the required form.

**Comment by tiroj** [comment]
[I think you closed the wrong issue: this one should be left open for comment, but the duplicate 810 issue should be closed.]

The form you show with a subscript –Ka below the virama form of R– would be read as RK, i.e. with the final inherent vowel suppressed. So this would be encoded as:

Ra + [ZWJ] + virama + Ka + virama

However, some fonts may not display this correctly due to the way in which they order the lookups or filter marks to handle the final virama ligating with the base Ra. So some fonts will produce this sort of error:
![image](https://user-images.githubusercontent.com/5614500/128223942-1081c4fc-3363-4727-a3da-65a80c93122f.png)

**Comment by tiroj** [comment]
[@alib-ms This will need to be fixed in the Nirmala fonts, so I will include that in the work this month.]

**Comment by N-Anbarasan** [comment]
Thanks for the response.
I solved this issue in my font.
