### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by tuncayofficial** [MicrosoftDocs/typography-issues#826]
[Enter feedback here]
How can I download fonts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
The Segoe UI fonts ship with Windows and are available as part of [Windows app design toolkits](https://docs.microsoft.com/en-us/windows/apps/design/downloads/), but aren't otherwise offered for free download. To use in other contexts, however, separate licenses can be obtained: see https://www.fonts.com/content/microsoft-typography.

**Comment by Zexyp** [comment]
Just
`C:\Windows\Fonts`
