### ISSUE TITLE
Tag registration

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#872]
The section named "How to register a design-variation axis tag" does not, in the end, describe how to register a design-variation axis tag... "Microsoft welcomes nominations for new design-variation axis tag registration." is as close as it comes. How should such nominations be submitted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cafec77-2f87-b614-3502-243b361ce877
* Version Independent ID: e002a131-e1ad-1a81-4e50-0b3ce56f605f
* Content: [OpenType Design-Variation Axis Tag Registry (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg)
* Content Source: [typographydocs/opentype/spec/dvaraxisreg.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/dvaraxisreg.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
@simoncozens  Was this intended to be in relation to registration of design-variation axis tags or, rather, to registration of language system tags (a request for which you also opened an issue at about the same time as this issue)?

**Comment by simoncozens** [comment]
Yes and no. When hoping to register a language tag, I went looking for how it should be done. Since I didn’t find any clarity on how to register a language tag, I looked at the other tag registry pages, and found that unlike other tags, the axis tag page does discuss how to register an axis tag - but doesn’t give details of the nomination process.

**Comment by PeterCon** [comment]
For OT 1.9, I'll add something to the Language System Tags page. (I think this was made clear at some point in the past, but got dropped along the way as communication channels also changed.)

For axis tags, it's a bit different since that's somewhat more involved.

**Comment by PeterCon** [comment]
For registering design axis tags, we tried setting up a process using a dedicated repo, <https://github.com/microsoft/OpenTypeDesignVariationAxisTags>. But it didn't really succeed, mainly because we didn't fully anticipate what would be needed to iterate on proposals to get at (i) what would be broadly useful and likely to be supported in apps, and (ii) how to spec details like the axis scale.

The [dvaraxisreg](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxisreg) page could point to that other repo, but I'm not sure that would be most useful right at this time (until we work out better processes). That page could simply suggest opening an issue in the typography-issues repo (as I've added for languagetags), but I'm still not sure if that would help much&mdash;it's not like many people are proposing new registered axes (much narrower group than for language system tags).

**Comment by simoncozens** [comment]
> it's not like many people are proposing new registered axes 

Maybe it's because they don't know how. ;-)

**Comment by tiroj** [comment]
The initial process presumed something like that which resulted in registration of the five initial OT variation axes, i.e. the submission of a formal axis specification with appropriate details of axis scale units, intended software interactions, and so forth. This failed early because, unlike those five initial axes—for which existing scale unit models and software interaction already existed—, new axes were being invented from scratch, and no one knew exactly how they should work because no one had worked with them or with non-variable equivalents in the same way they had with weight, width, etc.

On the fringes of the TYPO Labs event in Berlin, a group of us talked about re-fashioning the axis registration repo as a sandbox, i.e. a place to collect and develop ideas and proof-of-concept fonts for new axes, where the formal axis specification would be at the _end_ of the process, rather than at the beginning. I still think that would have been a good idea, but since MS owns the repo, it is up to them to decide whether to do that work.

In the meantime, I understand Type Network and Google Fonts have created an ad hoc registry for custom variation axes, along the lines of the sandbox idea. So maybe what we should look at is a path from that sandbox into the OT specification stream?

[That said, I am not sure it makes much sense to formally register more axes in the OT spec registry until the model for axis interaction—the avar2/xvar concepts—is agreed on and spec’d, because that may determine how some aspects of future low level parametric and user-facing optical axes are defined.]

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
