### ISSUE TITLE
Language tag request: Thai Mon

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#873]
I'd like to propose a new language tag for the Thai Mon language, a variant of the Mon language used in Thailand. As mentioned in [UTC document L2/20-163](https://www.unicode.org/L2/L2020/20163-arakanese-mon.pdf), Thai Mon has distinct orthographic forms, which fonts supporting the language need to be able to select. Arakanese (also known as Rakhine), the other language in that UTC document, already has the `ARK ` tag, but Thai Mon does not.

I propose the tag `THM ` for this language.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by dscorbett** [comment]
Is Thai Mon the same language as Aheu (ISO 639 tag `thm`)?

**Comment by simoncozens** [comment]
No, very different. Aheu is Vietic, Thai Mon is Monic. I don't know why Aheu got `thm`, but it wouldn't be the first case where the OTL tag is confusable with the ISO 639 tag.

**Comment by PeterCon** [comment]
Two things:
- While there are cases of OTL tags that conflict with ISO 639 IDs, it would be better to avoid creating conflicts. A four-letter tag (i.e., one without a trailing space) would be better&mdash;e.g., `mnwt`.
- To support interoperability, there needs to be clarity as to what the intended semantic is. For a case like this, that would mean pointing to external, stable documentation. The Unicode doc registry is stable; does L2/20-163 sufficiently document what typographic distinctions this tag is intended to indicate?

**Comment by simoncozens** [comment]
> A four-letter tag (i.e., one without a trailing space) would be better—e.g., mnwt.

Good idea - let's do that.

> The Unicode doc registry is stable; does L2/20-163 sufficiently document what typographic distinctions this tag is intended to indicate?

Yes, pages 9 onwards have tables of comparison between standard Burmese and Thai Mon forms of the glyphs.

**Comment by PeterCon** [comment]
Thanks.

Also, the description "Thai Mon" is confusing since "Thai" is a language name, but what is intended is not some creole language. Would "Thailand Mon" work?

**Comment by PeterCon** [comment]
Also, since "MON " is already used for Mon, what about "MONT" for this language system?

**Comment by simoncozens** [comment]
Going to have to defer to @ohbendy on the language name question. Ben, what do Thai Mon users call their language?

**Comment by ohbendy** [comment]
It seems to me this calls for a script variant rather than a language tag. As I mentioned in that Unicode document:

> In Burma, Mon language is now written in Burmese script, with additional, specific Mon characters. In Thailand, however, (and occasionally, historically, in Burma) although Mon language is also written with the Burmese script, there are significant differences in several letterforms. 

That is to say Mon is _one single language spoken in Burma and Thailand written using the same characters_: we're not looking at a different language or script. The form of some of those characters is what differs. The parallel here seems to be Syriac, which I understand has the general language tag of SYR and then four-letter tags SYRE, SYRJ, SYRN for Estrangela, Western and Eastern script variants. I believe a similar script-variant system is under consideration for the different styles of Tham script (Lanna, Lao-Isaan, Khuen/Lue). For our Mon case I think MNWT would be appropriate.

**Comment by ohbendy** [comment]
Interesting! Thanks for the explanation Peter. It all sounds reasonable to me, though as you can probably tell I'm not familiar with the underlying data structures and how it all works technically, I just wanna make our fonts as comprehensive as they can be. Should we seek input from others or go ahead with your suggestion?

**Comment by PeterCon** [comment]
If there are no concerns with the OT language system tag 'MONT' (alongside the existing tag 'MON ') and the description "Thailand Mon", then I'll add that in the registry.

**Comment by tiroj** [comment]
Ben, the key thing to remember is that OTL uses ‘language system’ tags, not language tags. The intent is to be able to capture differences in the typography of writing systems, which may correlate to languages but also to variant conventions within a language, e.g. as used in different communities.

The script tags need to map to Unicode script properties, so that a shaping engine can identify the script property of characters in the text run and know where to pass them for glyph processing. Hence, script variant tags are not a thing in OTL, because you don’t want ambiguity at that first stage of script itemisation and run segmentation.

So any writing system variant needs to be captured at either
a) the font level, i.e. different fonts for different languages or writing system variants using a script;
b) the language system tag level; or
c) a stylistic variant level (which may be the case if variants are not clearly correlated to language systems)

**Comment by ohbendy** [comment]
Thank you for taking the time to explain, John. It's all very clever and subtle, I wish I had a better grasp, but it's starting to make sense :)

**Comment by PeterCon** [comment]
I've added what I propose to the [OT 1.9 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec190/ot190beta).

**Comment by simoncozens** [comment]
Thanks very much for this, Peter. Ben, does "Thailand Mon" work for a name?

**Comment by ohbendy** [comment]
It seems fine to me but I don't think I'm really qualified to comment with such a sketchy understanding of all this.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
