### ISSUE TITLE
otvo_fig26a.png

### ISSUE THREAD

**Issue by miguelsousa** [MicrosoftDocs/typography-issues#917]
The illustration below is missing `• Deltas for peak at (1, -1)` on the lower-right corner of the variation space.
<img width="1188" alt="otvo_fig26a" src="https://user-images.githubusercontent.com/2119742/157958031-2c27d188-bb03-41d8-a77e-1c5419d7018f.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ea55ee-53f0-15da-1819-6dbbd9ae0e51
* Version Independent ID: 5746bf07-2094-52b3-3285-dadc590006c7
* Content: [OpenType Font Variations overview (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview)
* Content Source: [typographydocs/opentype/spec/otvaroverview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvaroverview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by bungeman** [comment]
This is labeled "Two-axis font with default at minimum for one axis". The illustration seems fine if you add in the implicit regions and correctly interpret the 0 axis values, and probably really good given that it shows how variations are often misunderstood. While many font editors push the idea that there are "masters at the corners" (an idea core to the Multiple Master format) there is no such requirement with OpenType Variations. In OpenType Variations there is one "master" (the default instance which is what is in the `glyf` table) and then there are regions which have a peak point at which a set of deltas are fully applied. There is no need to have a peak in any of the corners.

What this diagram is missing is the regions and a way to express when the "peak" is a set of edges and not a point. This is difficult to show here because there is a lot of overlapping. For example, in this diagram, the (0,1) peak would be best shown as the entire top line (the 0 here means that the peak is really spread out along that line) with a region of the top half. The (1,1) peak is a point with a region which is also the top half. The (1,0) peak on the right would have the whole box as a region with the peak really being the entire right side. The (0,-1) peak's region would be the lower half with the peak really being the entire bottom side.

While I have no suggestion for visualizing all these overlapping regions, it may be helpful if these illustrations added additional short line segments sticking out perpendicular to the 0 axis. That is to say, have some short blue blue lines or arrows pointing out from the (0,1) peak to the right, the (1,0) point up and down, and the (0, -1) point to the right. The current illustration makes these peaks look like actual points (they are encoded that way, but that's something of a clever hack) when they're really edges.

**Comment by PeterCon** [comment]
As @bungeman indicates, corner masters are entirely optional. I'll add text after that figure explaining that.

There is some explanation in that page describing the regions over which deltas are applicable. More figures could certainly help in explaining, but I don't have any indication that what's provided in the spec isn't adequate for guiding implementations to do the right thing.

**Comment by PeterCon** [comment]
See the OT 1.9.1 alpha for draft revisions addressing this issue.

**Comment by bungeman** [comment]
On the alpha page in the edit related to this there is an instance of `maximan` which should be `maximum`.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
