### ISSUE TITLE
OTSpec descriptions for fsSelection Bit 6 and Name ID 2 are contradictory

### ISSUE THREAD

**Issue by glenda-tn** [MicrosoftDocs/typography-issues#936]
In the OT Spec, the _fsSelection Bit 6_ description says:

> Bit 6: If bit 6 is set, then bits 0 and 5 must be clear, else the behavior is undefined. Note that, if both bit 0 and bit 5 are clear, that does not give any indication as to whether or not bit 6 will be clear. For example, **Arial Light is not the regular style of Arial and would have all bits cleared.**

while in the description for _Name ID 2 (Font Subfamily Name)_ there is this statement:

> This four-way distinction should also be reflected in the [OS/2.fsSelection](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fss) field, using bits 0 and 5. A font with no distinctive weight or style (e.g. medium weight, not italic, **and OS/2.fsSelection bit 6 set)** should use the string “Regular” as the Font Subfamily name (for English language).

It seems that leaving Bit 6 clear for styles such as Thin or SemiBold does _not_ have any adverse effect to style-linking with the Italic family member. However, after checking many different typeface families, we do notice that Bit 6 is set. 

Should Bit 6, in fact, be set for non-RIBBI fonts using Regular as the style in Name ID 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#fsselection)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by glenda-tn** [comment]
Hello,
Please have a look at this issue and confirm which is the correct specification. It's has been my understanding that Bit 6 should be on for all non-RIBBI, non-Italic styles that are set to "Regular" in the Style Name (ID 2). What are the ramifications if Bit 6 is **not** checked?

Yes or No? Do non-RIBBI styles (Thin, Light, SemiBold, etc.) need to have fsSelection bit #6 explicitly turned on?

Thank you,
Glenda

**Comment by PeterCon** [comment]
I'll need some time to investigate how bit 6 (defined back in 1990) is currently used.

**Comment by glenda-tn** [comment]
Hi @PeterCon. Just FYI, in our testing, we haven't seen ramifications either way with the bit on/off. IMO, it makes sense for it to be ON simply based on the fact that it would then correspond to Style Name ID 2, which is 'Regular' for all non-RIBBI styles. Some font editors (Glyphs) set the bit on by default while others (RoboFont) do not.

**Comment by glenda-tn** [comment]
@PeterCon Hi. New fonts are being created daily; I'd really like to be able to advise our Foundry Partners on the proper setting. For now, depending on the work flow, both options are being used.

**Comment by PeterCon** [comment]
@glenda-tn I don't think the statements are contradictory. It's just a bit vague as to _when_ bit 6 should be set. For a family with various weights/widths/etc., my inclination would have been to say that bit 6 is set only for the one font in that family that is the Regular for the entire family, not for each non-RIBBI font that happens to have name ID 2 set to "Regular" to accommodate apps that require a RIBBI family model. But I'd defer to what is actually needed to make fonts work in existing software.

It turns out that there doesn't appear to be much that checks bit 6. I investigated GDI, DWrite, Apple's Core Text, Harfbuzz, Adobe apps. Bit 0 (italic) gets used in many places, and also bits 5 (bold) and 9 (oblique) in some contexts. Bit 7 (USE_TYPO_METRICS) is also used heavily, though it's orthogonal to style description bits and names.

Given this, I'm not sure what might be said in the spec to clarify, but I'll come up with some draft for OT 1.9.1 (in progress).

**Comment by PeterCon** [comment]
I've prepared revisions for the 'name' and OS/2 chapters of the OT spec. See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by glenda-tn** [comment]
I finally saw the draft revision and the edits you made clarify it. Deleting the sentence in the description of Name ID 2 prevents the confusion I was having. Thanks @PeterCon.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
