### ISSUE TITLE
Add CJK fixed-pitch font remarks for xAvgCharWidth

### ISSUE THREAD

**Issue by sgwaki** [MicrosoftDocs/typography-issues#938]
When using CJK fixed-pitch font on Windows, double of xAvgCharWidth scaled value seems to be used for full-width glyph advance. In practice, the value should be a half-width glyph width, not an average of all non-zero width glyphs. So, we should add remarks regarding these points.

xAvgCharWidth description in OpenType 1.4+ specification says "The Average Character Width parameter specifies the arithmetic average of the escapement (width) of all non-zero width glyphs in the font". If a CJK fixed-pitch font follows the description, xAvgCharWidth value is nearly full-width glyph width because it has over 6,000 full-width ideograph glyphs and only 158 half-width glyphs. Using the font on Windows, it will show unnatural horizontal spaces between full-width characters, e.g. Hiragana and Ideograph.

MS Gothic is the typical Japanese fixed-pitch font. Though it's OS/2 table version is 3, xAvgCharWidth is half-width glyph width, i.e. 128 while UnitsPerEm is 256.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#feedback)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Some older fonts might have been updated with the OS/2 version changed but with the xAvgCharWidth left the same. Strictly speaking, that doesn't conform to the spec, though the font developers might have done that because they thought there was less compatibility risk, or maybe they overlooked it (e.g. maybe they updated the OS/2 version to take advantage of a newer field and forgot to check this).

In any case, applications should no be relying on xAvgCharWidth for getting glyph advance widths or calculating layout of lines of text.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
I'm not aware of any issues using MS Gothic in GDI.

**Comment by sgwaki** [comment]
MS Gothic seems to follow the old calculation method for xAvgCharWidth in OS/2 table.
Have you tried a CJK fixed-pitch font using new (v3) calculation method for xAvgCharWidth in OS/2 table in GDI?

If you haven't, I suggest trying out VL-Gothic 20200720. It's avaiable from https://osdn.net/projects/vlgothic/downloads/73361/VL-Gothic-Regular.ttf/ .  As seen in the following screenshot, it shows unnatural spaces between Japanese letters in GDI:
![vl-gothic-20200720](https://user-images.githubusercontent.com/13335852/186914464-7c0d05ec-693c-428f-84c2-ce176cc1965c.png)

At least, the specification should note this compatibility risk.

**Comment by PeterCon** [comment]
I suspect this might be an application-specific issue rather than something affecting GDI itself. I don't have access to a Windows machine this week to investigate but will do so next week.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.

**Comment by aaronbell** [comment]
@PeterCon Google Fonts has recently received a [bug report](https://github.com/google/fonts/issues/9196) on this same issue with a set of fonts that have `post.FixedPitch` set to 1, but have a `v3` `OS/2` table with a non-compatible `xAvgCharWidth` value. 

It is unclear if the correct solution is to remove the bit, change the `xAvgCharWidth` to follow legacy standards (and not conform to the spec), or if the problem is on Windows' side and Microsoft needs to address. 

Can you advise?

**Comment by PeterCon** [comment]
It turns out there's more here that I wasn't able to discover when this was first raised in 2022. Apparently, GDI has code that treats xAvgCharWidth as half the ideograph width. (I'm guessing the rationale is based on the version 0 spec, using a-z to calculate xAvgCharWidth, but in CJK implementations those are all _half width characters_.) For that reason, at least some fonts, such as Simsun, have set the value to half of the actual ideograph width. I haven't seen the actual GDI code, so don't know the exact details or if it treats fonts with post.FixedPitch set any differently.

**Comment by kojiishi** [comment]
FYI, from a developer of rendering engines point of view.

My understanding on `xAvgCharWidth` is that it's an average of widths of glyphs _excluding CJK characters_, regardless fixed-pitch or not, though, it's not easy to define "excluding CJK characters" clearly in the Unicode era.

[This comment](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/layout/forms/layout_text_control.cc;l=142-143;drc=e97d2fadb1598226b64ed1e49845a7f8e53641b5;bpv=1;bpt=1) in the Chromium may be interesting:
```c++
bool LayoutTextControl::HasValidAvgCharWidth(const Font& font) {
  // Some fonts match avgCharWidth to CJK full-width characters.
  // Heuristic check to avoid such fonts.
  if (metrics.HasZeroWidth() &&
      font_data->AvgCharWidth() > metrics.ZeroWidth() * 1.7)
    return false;
```
