### ISSUE TITLE
Named instance at default location

### ISSUE THREAD

**Issue by justvanrossum** [MicrosoftDocs/typography-issues#946]
For a named instance at the default location, the spec says the following:

> If an instance record is included for the default instance (that is, an instance record has coordinates set to default values), then the nameID value should be set to either 2 or 17, and the postScriptNameID value should be set to 6.

Isn't this too strong? Why must it be (one of) those exact name IDs, and can't it be an equivalent value? Currently, fontmake doesn't use 2 or 17 in this case, even when the actual value is the correct one (as set in the designspace source file).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e09c4e08-f5d6-6887-1677-a346f098d22d
* Version Independent ID: 3c46b51b-529b-ff70-00d3-64950c372348
* Content: [fvar — Font Variations Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar)
* Content Source: [typographydocs/opentype/spec/fvar.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/fvar.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by anthrotype** [comment]
I also believe it's too strong. Instead of "should be set to either 2 or 17", there should be a "could be set...". This would also better align with the preceding sentences where it says "can be used", and if used at all, then they should only be used for default instance, see: 

> Values of 2 or 17 can be used; ... The values 2 or 17 should only be used if the named instance corresponds to the font’s default instance.

In addition to the instance's subFamilyNameID, there is also a related issue that arise from a literal interpretation of the spec, the one concerning the postScriptNameID. The sentence Just quoted above from the spec says

> If an instance record is included for the default instance ... the postScriptNameID value should be set to 6.

But the postScriptNameID field is "optional", says a previous sentence, which continues

> All of the instance records in a given font must be the same size, with all either including or omitting the postScriptNameID field.

From this, the fontbakery QA tool concluded that, if a named instances matches the default instance, then it must declare an explicit postScriptNameID=6 and because a postScriptNameID was included in one instance, the all the instances must also have that (to make instance record the same size), thus unnecessarily bloating the name table with extra stuff that could be derived at runtime.

So, I think also this "the postScriptNameID value _should_ be set to 6" should be relaxed. It would suffice to say that, if can be used (but one does not have to necessarily set it), and i used at all, can only be set for the default instance.

**Comment by anthrotype** [comment]
ok, it's also true that "An instance record is not required for the default instance, though an instance record can be provided" -- so if one wanted to avoid that situation, one could omit the instance record for the default instance

**Comment by PeterConstable** [comment]
>Why must it be (one of) those exact name IDs... ?

It's not a requirement; it's a recommendation ("should").

>can't it be an equivalent value?
Please clarify or give an example or two.

@justvanrossum  or @anthrotype :  It will help to explain why this recommendation is too strong.

Regarding postScriptNameID, it seems reasonable to revise that clause to

>... and the postScriptNameID, if included, should be set to 6.

**Comment by justvanrossum** [comment]
I think even just a recommendation for 2 and 17 is too strong: people tend to read recommendations as requirements. It should be enough for the field referenced by subFamilyNameID to be equal in value to 2 or 7.

If recommendations can be ignored at will, what value do they have?

**Comment by PeterConstable** [comment]
@justvanrossum Please give an example of something "equal in value to [but not the same as] 2 or 17" and why that might be preferable.

IIRC, the recommendation was agreed upon back in 2016 as a way to provide the best compatibility with existing software that doesn't support variations. It's not obvious why that wouldn't make sense to recommend.

**Comment by PeterConstable** [comment]
Thanks; that clarifies.

So, would the following work?

> If an instance record is included for the default instance (that is, an instance record has coordinates set to default values), then the nameID value should be set to 2 or 17 or to a name ID with the same value as name ID 2. Also, if a postScriptNameID is included in instance records, the value for the default instance should be set to 6 or to a name ID with the same value as name ID 6.

**Comment by justvanrossum** [comment]
Yes, thank you, to me that's a huge improvement.

> with the same value as name ID 2.

Should that be "with the same value as name ID 2 or 17" as well?

**Comment by PeterConstable** [comment]
Yes, I suppose so.

I'll make this change in OT 1.9.1 (in preparation).

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
