### ISSUE TITLE
UnderlinePosition

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#951]
The UnderlinePosition is defined like this:

> UnderlinePosition: Equivalent to the underlinePosition field in the 'post' table.

In CFF, it seems to me defined as (from the post table spec):
> The PostScript definition of this FontInfo dictionary key (the y coordinate of the center of the stroke) is not used for historical reasons. The value of the PostScript key may be calculated by subtracting half the underlineThickness from the value of this field.

The CFF2 spec should make it clear that this was changed. 

And why aren't there more details for the CFF table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3f1db1-b1f0-587c-0dbe-9e090b32c5d9
* Version Independent ID: 49bd6461-28c0-a133-77b1-617b8f2f5dab
* Content: [CFF2 - Compact font format version 2 table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2)
* Content Source: [typographydocs/opentype/spec/cff2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
In the CFF2 chapter, the UnderlinePosition operator is listed in a table of TopDICT operators not used in CFF2. It doesn't make sense to describe in the CFF2 chapter differences pertaining to an operator not used in CFF2 at all.

For OT 1.9.1, appendix D will be dropped from the CFF2 chapter, as part of a re-write of that chapter&mdash;see the [current draft](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/cff2). The old appendex D will be superseded by a new (spec-level) appendix summarizing differences between 'glyf' 'CFF ' and CFF2 tables&mdash; see the current draft of this appendix, [Comparison of 'glyf', 'CFF ' and CFF2 tables](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/glyphformatcomparison).

>And why aren't there more details for the CFF table?

Your issue seems to have arisen from comparison between a CFF TopDICT operator versus the similar 'post' field. For 25+ years it has sufficed to document 'CFF' by reference to Adobe's external specification, and there's no plan to change that.

See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions to related portions of the spec.

(Closing since no further action is anticipated.)
